<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 13               */
/* CACHE FILE: Generated: Sat, 22 Dec 2012 23:42:16 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_ibEconomy2_13 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['item_row'] = array('need_preview_link');
$this->_funcHooks['lottery_row'] = array('num_lotto_balls','num_lotto_balls','num_lotto_balls','eco_lottery_still_open','eco_lottery_still_open','eco_lottery_still_open','eco_lottery_still_open','eco_lottery_still_open','eco_lottery_my_tickets','eco_lottery_still_open');
$this->_funcHooks['myCC'] = array('cc_csh_adv','cc_bal_trsnr');
$this->_funcHooks['myShopItem'] = array('item_is_usable','item_can_sell','item_can_trade');
$this->_funcHooks['myStock'] = array('can_sell_stock');
$this->_funcHooks['usingItem'] = array('usingitemhtmlrows','using_item_html');


}

/* -- bank_row --*/
function bank_row($bank) {
$IPBHTML = "";
$IPBHTML .= "<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=add_to_cart' method='post'>
	<input type='hidden' name='item_id' value='bank_{$bank['b_id']}_{$bank['type']}' />
		<p class='message'><img src='{$this->settings['img_url']}/information.png' /> {$this->lang->words['description']}: {$bank['desc']}</p><br />
		<ul class='ipsForm ipsForm_horizontal'>
			<li class='ipsField'>{$this->lang->words['apy']}: {$bank['apy']}</li>
			<li class='ipsField'>
				<label class='ipsField_title'>{$this->lang->words['dep_amount']} <spanclass='ipsForm_required'>*</span></label>
				<div class='ipsField_content'>
					<input type=\"text\" class='input_text' id='quantity' name=\"quantity\" size=\"3\" /><br />
				</div>
			</li>
		</ul>
	<fieldset class='submit'>
		<input type='submit' class='input_submit' value='{$this->lang->words['add_to_cart']}' />
	</fieldset>
	</form>";
return $IPBHTML;
}

/* -- bankLoanRows --*/
function bankLoanRows($bank) {
$IPBHTML = "";
$IPBHTML .= "<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=add_to_cart' method='post'>
	<input type='hidden' name='item_id' value='bank_{$bank['b_id']}_loan' />
		<p class='message'><img src='{$this->settings['img_url']}/information.png' /> {$this->lang->words['description']}: {$bank['desc']}</p><br />
		<ul class='ipsForm ipsForm_horizontal'>
			<li class='ipsField'>{$this->lang->words['overdue_penalty']}: {$bank['b_loans_pen']}{$this->lang->words['%']}</li>
			<li class='ipsField'>{$this->lang->words['global_outstanding_loan_amount']}: {$this->settings['eco_general_cursymb']}{$bank['outstanding_loan_amt']}</li><br />	
			<li class='ipsField'>
				<label class='ipsField_title'>{$this->lang->words['Loan_Amount']} <spanclass='ipsForm_required'>*</span></label>
				<div class='ipsField_content'>
					<input type=\"text\" class='input_text' id='quantity' name=\"quantity\" size=\"3\" /><br />
				</div>
			</li>
		</ul>
	<fieldset class='submit'>
		<input type='submit' class='input_submit' value='{$this->lang->words['request_loan']}' />
	</fieldset>
	</form>";
return $IPBHTML;
}

/* -- cc_row --*/
function cc_row($cc='') {
$IPBHTML = "";
$IPBHTML .= "<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=add_to_cart' method='post'>
	<input type='hidden' name='item_id' value='cc_{$cc['cc_id']}' />
		" . (($cc['cc_csh_adv']) ? ("
		<ul class='ipsForm ipsForm_horizontal'>
			<li class='ipsField'>{$this->lang->words['bal_transfer_apr']}: {$cc['cc_bal_trnsfr_apr']}</li>
			<li class='ipsField'>
				<label class='ipsField_title'>{$this->lang->words['cash_advance']}</label>
				<div class='ipsField_content'>
					<input type=\"text\" class='input_text' id='quantity' name=\"quantity\" size=\"3\" /><br />
				</div>
			</li>
			") : ("")) . "
		</ul>
		</if>
	<fieldset class='submit'>
		<input type='submit' class='input_submit' value='{$this->lang->words['add_to_cart']}' />
	</fieldset>
	</form>";
return $IPBHTML;
}

/* -- invest_rows_wrapper --*/
function invest_rows_wrapper($content='',$pages='') {
$IPBHTML = "";
$IPBHTML .= "<fieldset style='margin: 0px;padding:0px;'>
        <div id='member_list' class='clear block_wrap' style='padding:0px;margin:0px;'>
	        <div id='member_wrap' >
		        <ul class='members' >		
					{$content}
				</ul>
            </div>
        </div>
		<div style='margin:10px;'>
			{$pages}
		</div>
</fieldset>";
return $IPBHTML;
}

/* -- item_row --*/
function item_row($item, $singleItem=False) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy2', $this->_funcHooks['item_row'] ) )
{
$count_ca05e97dd517e20d34d3ae6da2a0494d = is_array($this->functionData['item_row']) ? count($this->functionData['item_row']) : 0;
$this->functionData['item_row'][$count_ca05e97dd517e20d34d3ae6da2a0494d]['item'] = $item;
$this->functionData['item_row'][$count_ca05e97dd517e20d34d3ae6da2a0494d]['singleItem'] = $singleItem;
}
$IPBHTML .= "<tr class='__topic expandable' id='trow_{$item['cart_item_id']}' data-id=\"{$item['cart_item_id']}_{$item['cart_item_bank_type']}\" data-type=\"{$item['cart_item_type']}\" bank-type=\"{$item['cart_item_bank_type']}\">
	<td class='row2' style='text-align:center;width:10%;margin:5px'>
		<span>{$item['image_thumb_link']}</span>
	</td>
	<td class='col_f_content' style='width:40%;'>
		<h4>{$item['cart_item_title']} <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab={$item['cart_item_tab']}&amp;area=single&amp;type={$item['cart_item_type']}&amp;id={$item['cart_item_id']}&amp;bank_type={$item['cart_item_bank_type']}' class='__item __id{$item['cart_item_id']}__type_{$item['cart_item_type']}_{$item['cart_item_bank_Type']}' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a></h4>
		<br />
		<span class='desc lighter blend_links'>
			{$item['cart_item_more_info']}
		</span>
	</td>
	" . ((!$singleItem) ? ("
		<td class='col_f_preview __item_preview'>
			<a href='{$this->settings['base_url']}app=ibEconomy&amp;tab={$item['cart_item_tab']}&amp;area=single&amp;type={$item['cart_item_type']}&amp;id={$item['cart_item_id']}&amp;bank_type={$item['cart_item_bank_type']}' class='expander closed' title='{$this->lang->words['view_more_and_purchase']}'>&nbsp;</a>
		</td>
	") : ("")) . "
	<td class='col_f_post'> 
		<ul>
			<li class='views desc'><img src='{$this->settings['img_url']}/eco_images/money_dollar.png' />&nbsp;{$item['cost_text']}: {$item['cost']}</li>
			<li class='views desc'><img src='{$this->settings['img_url']}/user.png' />&nbsp;{$item['num_purchased_text']}: {$item['num_purchased']}</li>
			<li class='views desc'><img src='{$this->settings['img_url']}/eco_images/{$item['right_fields_1_image']}' />&nbsp;{$item['right_fields_1_text']}: {$item['right_fields_1']}</li>
		</ul>
	</td>
</tr>";
return $IPBHTML;
}

/* -- items_wrapper --*/
function items_wrapper($content, $headerTitle, $pages='') {
$IPBHTML = "";
$IPBHTML .= "<div class='maintitle'>{$headerTitle}</div>		
		<div class='ipsBox table_wrap'> 
			<div class='ipsBox_container'> 		
				<table class='ipb_table'>
					{$content}
				</table>
			</div>
		</div>
		<div style='margin:10px;'>
			{$pages}
		</div>";
return $IPBHTML;
}

/* -- lottery_row --*/
function lottery_row($lotto) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy2', $this->_funcHooks['lottery_row'] ) )
{
$count_35b5370303dafad4636bab5ba032ef24 = is_array($this->functionData['lottery_row']) ? count($this->functionData['lottery_row']) : 0;
$this->functionData['lottery_row'][$count_35b5370303dafad4636bab5ba032ef24]['lotto'] = $lotto;
}
$IPBHTML .= "" . (($lotto['your_num_total_tix'] > 0) ? ("" . (($lotto['your_num_tix'] > 0) ? ("
				<p class='message error'><img src='{$this->settings['img_url']}/eco_images/tag_blue_edit.png' />{$this->lang->words['lotto_pick_remind']}</p>
				<br />
			") : ("")) . "
			" . (($lotto['tix_still_4_sale'] and $lotto['your_num_tix'] > 0) ? ("
				<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=submit_lotto_picks' method='post'>
			") : ("")) . "
			" . (($lotto['your_num_tix'] > 0 || $lotto['your_num_picked'] > 0) ? ("<div class='maintitle'>{$this->lang->words['your_tickets']}</div>
			<table class='ipb_table'>
				<tr class='header'>
					<th>Ticket</th>
					".$this->__f__f0546375eb5b974b3e3b995a8a465ff3($lotto)."				</tr>
				".$this->__f__699dc3a0215b6cad5d38f6713f534e96($lotto)."			</table>
			" . (($lotto['tix_still_4_sale'] and $lotto['your_num_tix'] > 0) ? ("
				<fieldset class='submit'>
					{$this->lang->words['or_get_random_values']}&nbsp;&nbsp;
					<input type = 'checkbox' name='use_random_nums' />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<b>{$this->lang->words['make_your_picks_then_submit']}...&nbsp;</b>
					<input type='submit' class='input_submit alt' value='{$this->lang->words['go']}' />
				</fieldset>	
				") : ("")) . "
				</form>") : ("")) . "") : ("" . (($lotto['tix_still_4_sale']) ? ("
			<p class='message'><img src='{$this->settings['img_url']}/information.png' /> {$this->lang->words['description']}: {$this->lang->words['lotto_description']}</p><br />
			") : ("")) . "")) . "
		<br /><br />
		" . (($lotto['tix_still_4_sale']) ? ("
			<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=add_to_cart' method='post'>
				<input type='hidden' name='item_id' value='lottery_{$lotto['l_id']}' />		
				<ul class='ipsForm ipsForm_horizontal'>
					<li class='ipsField'>
						<label class='ipsField_title'>{$this->lang->words['num_to_purchase']} <spanclass='ipsForm_required'>*</span></label>
						<div class='ipsField_content'>
							<input type=\"text\" class='input_text' id='quantity' name=\"quantity\" size=\"3\" /><br />
						</div>
					</li>
				</ul>
			<fieldset class='submit'>
				<input type='submit' class='input_submit' value='{$this->lang->words['add_to_cart']}' />
			</fieldset>
			</form>
		") : ("
			{$this->lang->words['winning_numbers']}: {$lotto['winning_numbers']}
		")) . "";
return $IPBHTML;
}


function __f__f0546375eb5b974b3e3b995a8a465ff3($lotto)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $lotto['lottoBalls'] as $lottoBall )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<th>{$lottoBall['header']}</th>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__f355d4824232c5f0ee3040043c413d75($lotto,$lottoTicket='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $lotto['lottoBalls'] as $lottoBall )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<td>{$lottoTicket['ballDD_'.$lottoBall['number']]}</td>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__699dc3a0215b6cad5d38f6713f534e96($lotto)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $lotto['myLottoTickets'] as $lottoTicket )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<tr id='{$log['l_id']}'>
					<td>{$lottoTicket['ticketNum']}</td>
					".$this->__f__f355d4824232c5f0ee3040043c413d75($lotto,$lottoTicket)."				</tr>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- lottery_wrapper --*/
function lottery_wrapper($content='', $pages='') {
$IPBHTML = "";
$IPBHTML .= "<fieldset style='margin: 0px;padding:0px;'>
				<div id='member_list' class='clear block_wrap' style='padding:0px;margin:0px;'>
					<div id='member_wrap' >
						<ul class='members' >		
							{$content}
						</ul>
					</div>
				</div>
				<div style='margin:10px;'>
					{$pages}
				</div>
		</fieldset>";
return $IPBHTML;
}

/* -- lt_row --*/
function lt_row($lt='') {
$IPBHTML = "";
$IPBHTML .= "<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=add_to_cart' method='post'>
	<input type='hidden' name='item_id' value='lt_{$lt['lt_id']}' />	
		<p class='message'><img src='{$this->settings['img_url']}/information.png' /> {$this->lang->words['description']}: {$lt['desc']}<br /><br />
			<i>{$this->lang->words['risk']}:</i> <strong>{$lt['lt_risk_level']}%</strong> - {$this->lang->words['risk_reward_exp']}<br /></p><br />
		<ul class='ipsForm ipsForm_horizontal'>
			<li class='ipsField'>{$this->lang->words['level_of_risk']}: <p style='margin-top:-11px;width:135px' class='progress_bar user_warn'  title='{$this->lang->words['level_of_risk']}: {$lt['lt_risk_level']}%'>
				<span style='width: {$lt['lt_risk_level']}%'><span>{$this->lang->words['risk_level']}: {$lt['lt_risk_level']}%</span></span></li>
			<li class='ipsField'>
				<label class='ipsField_title'>{$this->lang->words['to_invest']}</label>
				<div class='ipsField_content'>
					<input type=\"text\" class='input_text' id='quantity' name=\"quantity\" size=\"3\" /><br />
				</div>
			</li>
			</if>
		</ul>
		</if>
	<fieldset class='submit'>
		<input type='submit' class='input_submit' value='{$this->lang->words['add_to_cart']}' />
	</fieldset>
	</form>";
return $IPBHTML;
}

/* -- my_items_row --*/
function my_items_row($item) {
$IPBHTML = "";
$IPBHTML .= "<tr id='{$item['p_id']}'>
				<td class='altrow short'>
					{$item['image_thumb_link']}
				</td>
				<td>
					<span style='font-weight:bolder'>
						<a style='text-decoration:none;' href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=me&amp;area=single&amp;type=" . (($item['type_type'] == 'Loan') ? ("loan") : ("{$item['p_type']}")) . "&amp;id={$item['p_type_id']}" . (($this->request['area'] == 'my_banks') ? ("&amp;type_type={$item['type_type']}") : ("")) . "\">{$item['name']}</a> <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=" . (($item['p_type'] == 'shopitem') ? ("shop") : ("invest")) . "&amp;area=single&amp;type={$item['p_type']}&amp;id={$item['p_type_id']}" . (($item['p_type'] == 'bank') ? ("&amp;bank_type={$item['type_type']}") : ("")) . "' class='__item __id{$item['p_type_id']}__type_{$item['p_type']}_{$item['link_type_type']}' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a>
					</span>
				</td>
				<td>
					{$item['type_type']}
				</td>				
				<td class='altrow short'>
					{$item['value']}
				</td>
				<td class='short'>
					{$item['value2']}
				</td>
				<td  class='altrow short'>
					" . (($this->request['area'] != 'my_shopitems') ? ("{$this->settings['eco_general_cursymb']}") : ("")) . "{$item['total_value']}
				</td>
				<td class='short'>
					<a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=me&amp;area=single&amp;type=" . (($item['type_type'] == 'Loan') ? ("loan") : ("{$item['p_type']}")) . "&amp;id={$item['p_type_id']}" . (($this->request['area'] == 'my_banks') ? ("&amp;type_type={$item['type_type']}") : ("")) . "\"><img src='{$this->settings['img_url']}/eco_images/folder_magnify.png'></a>
				</td>
			</tr>";
return $IPBHTML;
}

/* -- my_items_wrapper --*/
function my_items_wrapper($content='', $colTitles='', $pages='') {
$IPBHTML = "";
$IPBHTML .= "<div class='maintitle'>{$this->lang->words['my_items']}</div>
		<table class='ipb_table'>
			<tr class='header'>
				<th scope='col'>&nbsp;</th>
				<th scope='col'>{$this->lang->words['name']}</th>
				<th scope='col'>{$colTitles['two']}</th>
				<th scope='col' class=' short'>{$colTitles['three']}</th>
				<th scope='col' class=' short'>{$colTitles['four']}</th>
				<th scope='col' class=' short'>{$colTitles['five']}</th>
				<th scope='col' class=' short'>{$this->lang->words['more']}</th>
			</tr>
            {$content}
		</table>
		<div style='margin:10px;'>
			{$pages}
		</div>";
return $IPBHTML;
}

/* -- myBank --*/
function myBank($bank) {
$IPBHTML = "";
$IPBHTML .= "<h3 class='bar' style='padding:3px;margin:0px'>{$bank['b_title']} - {$bank['type']} <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=invest&amp;area=single&amp;type=bank&amp;id={$bank['b_id']}&amp;bank_type={$bank['type']}' class='__item __id{$bank['b_id']}__type_bank_{$bank['type']}' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a></h3>		
					<table class='ipb_table'>
						<tr>
							<td>
								{$bank['image_thumb_link']}
							</td>
							<td colspan='4'>
								<table class='ipb_table'>
									<tr>
										<td style='width:33%;text-align:left'>
											<img src='{$this->settings['img_url']}/eco_images/money_dollar.png' alt='{$this->lang->words['total_funds']}' /> {$this->lang->words['total_balance']}: {$this->settings['eco_general_cursymb']}{$bank['total_value']}
										</td>
										<td style='width:1%' >
											&nbsp;
										</td>										
										<td style='width:33%;text-align:center'>
											<img  src='{$this->settings['img_url']}/eco_images/calendar.png' alt='{$this->lang->words['opened_on']}' /> {$this->lang->words['opened_on']}:  {$bank['open_date']}
										</td>
										<td style='width:33%;text-align:right'>
											<img  src='{$this->settings['img_url']}/eco_images/coins_add.png' alt='{$this->lang->words['apy']}' />	{$this->lang->words['apy']}: {$bank['apy']}
										</td>										
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td>
								&nbsp;
							</td>						
							<td>
								<strong>{$this->lang->words['dep_fee']}:</strong> {$bank['dep_fee']}<br /><br /><br />
								<strong>{$this->lang->words['with_fee']}:</strong> {$bank['wth_fee']}
							</td>
							<td style='text-align:right'>
								<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=bank_deposit' method='post'>
								<input type='hidden' name='item_id' value='{$bank['b_id']}_{$bank['type']}' />
								<p style='padding-bottom:15px;padding-right:10px;'>
									<input type='text' name='amount' value='{$this->lang->words['number_icon']}' onfocus=\"value=''\" size='4' />
								</p>
								<p class='reputation zero'>
									<img style='margin:1px 0px 6px 0px' src='{$this->settings['img_url']}/eco_images/money_add.png' alt='{$this->lang->words['make_deposit']}' title='{$this->lang->words['make_deposit']}' />&nbsp;		
									<input type='submit' class='input_submit' style='padding:2px 0px 2px 0px' name='submit' value='{$this->lang->words['make_deposit']}' />
								</p>
								</form>
							</td>	
							<td style='text-align:right'>
								<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=bank_withdrawal' method='post'>
								<input type='hidden' name='item_id' value='{$bank['b_id']}_{$bank['type']}' />
								<p style='padding-bottom:15px;padding-right:10px;'>
									<input type='text' name='amount' value='{$this->lang->words['number_icon']}' onfocus=\"value=''\" size='4' />
								</p>
								<p class='reputation zero'>
									<img style='margin:1px 0px 6px 0px'  src='{$this->settings['img_url']}/eco_images/money_delete.png' alt='{$this->lang->words['make_withdrawal']}' title='{$this->lang->words['make_withdrawal']}' />&nbsp;		
									<input type='submit' class='input_submit' name='submit' style='padding:2px 0px 2px 0px' value='{$this->lang->words['make_withdrawal']}' />
								</p>
								</form>
							</td>							
						</tr>
					</table>";
return $IPBHTML;
}

/* -- myCC --*/
function myCC($cc) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy2', $this->_funcHooks['myCC'] ) )
{
$count_38cd345737e727708a7f5ec2d4c78646 = is_array($this->functionData['myCC']) ? count($this->functionData['myCC']) : 0;
$this->functionData['myCC'][$count_38cd345737e727708a7f5ec2d4c78646]['cc'] = $cc;
}
$IPBHTML .= "<h3 class='bar' style='padding:3px;margin:0px'>{$cc['cc_title']} - {$this->settings['eco_general_cursymb']}{$cc['my_credit_line']} <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=invest&amp;area=single&amp;type=cc&amp;id={$cc['cc_id']}' class='__item __id{$cc['cc_id']}__type_cc_{$cc['type']}' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a></h3>
					<table class='ipb_table'>
						<tr>
							<td>
								{$cc['image_thumb_link']}
							</td>
							<td colspan='4'>
								<table class='ipb_table'>
									<tr>
										<td style='width:33%;text-align:left'>
											<img src='{$this->settings['img_url']}/eco_images/money_dollar.png' alt='{$this->lang->words['cur_card_balance']}' /> {$this->lang->words['cur_card_balance']}: {$this->settings['eco_general_cursymb']}{$cc['total_value']}
										</td>									
										<td style='width:33%;text-align:center'>
											<img  src='{$this->settings['img_url']}/eco_images/calendar.png' alt='{$this->lang->words['opened_on']}' /> {$this->lang->words['opened_on']}:  {$cc['open_date']}
										</td>
										<td style='width:33%;text-align:right'>
											<img  src='{$this->settings['img_url']}/eco_images/coins_add.png' alt='{$this->lang->words['apr']}' />	{$this->lang->words['apr']}: {$cc['apr']}
										</td>										
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan='5'>
								<table class='ipb_table' style='border-bottom:none'>
									<tr>
										<td style='width:30%;'>
											<span style='font-weight: bolder'>{$this->lang->words['min_due']}:</span>
											<span style='font-size:0.75em;'>{$this->settings['eco_general_cursymb']}{$cc['min_due']}</span><br />
											<span style='font-weight: bolder'>{$this->lang->words['by']}:</span>
											<span style='font-size:0.75em;'>{$cc['due_date']}</span>
										</td>
										<td style='width:30%;text-align:right'>
											<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=cc_payment' method='post'>
											<input type='hidden' name='item_id' value='{$cc['cc_id']}' />
											<p>
												<input type='text' name='amount' value='{$this->lang->words['number_icon']}' onfocus=\"value=''\" size='4' />
											</p>
										</td>
										<td style='width:40%;text-align:right'>
											<p class='reputation zero'>
												<img src='{$this->settings['img_url']}/eco_images/money_delete.png' alt='{$this->lang->words['make_payment']}' title='{$this->lang->words['make_payment']}' />&nbsp;		
												<input type='submit' class='input_submit' name='submit' value='{$this->lang->words['make_payment']}' />
											</p>
											</form>
										</td>
									</tr>
									" . (($cc['cc_csh_adv']) ? ("								
									<tr>
										<td>
											<span style='font-weight: bolder'>{$this->lang->words['csh_adv_fee']}:</span>
											<span style='font-size:0.75em;'>{$cc['cc_csh_adv_fee']}</span><br />
											<span style='font-weight: bolder'>{$this->lang->words['max']}:</span>
											<span style='font-size:0.75em;'>{$this->settings['eco_general_cursymb']}{$cc['cash_adv_max']}</span>
										</td>										
										<td style='text-align:right'>											
											<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=cash_advance' method='post'>
											<input type='hidden' name='item_id' value='{$cc['cc_id']}' />
											<p>
												<input type='text' name='amount' value='{$this->lang->words['number_icon']}' onfocus=\"value=''\" size='4' />
											</p>
										</td>
										<td style='text-align:right'>											
											<p class='reputation zero'>
												<img src='{$this->settings['img_url']}/eco_images/bullet_go.png' alt='{$this->lang->words['get_cash_advance']}' title='{$this->lang->words['get_cash_advance']}' />&nbsp;		
												<input type='submit' class='input_submit' name='submit' value='{$this->lang->words['get_cash_advance']}' />
											</p>
											</form>
										</td>
									</tr>
									") : ("")) . "
									" . (($cc['cc_bal_trnsfr'] && $cc['other_cards_dd']) ? ("									
									<tr>
										<td>
											<span style='font-weight: bolder'>{$this->lang->words['bal_transfer_apr']}:</span>
											<span style='font-size:0.75em;'>{$cc['cc_bal_trnsfr_apr']}</span><br />
											<span style='font-weight: bolder'>{$this->lang->words['until']}:</span>
											<span style='font-size:0.75em;'>{$cc['cc_bal_trnsfr_ends']}</span>
										</td>										
										<td style='text-align:right'>
											<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=balance_transfer' method='post'>
											<p>
												{$cc['other_cards_dd']}
											</p><br />
											<input type='hidden' name='item_id' value='{$cc['cc_id']}' />
											<p>
												<input type='text' name='amount' value='{$this->lang->words['number_icon']}' onfocus=\"value=''\" size='4' />
											</p>
										</td>
										<td style='text-align:right'>								
											<p class='reputation zero'>
												<img src='{$this->settings['img_url']}/eco_images/money_add.png' alt='{$this->lang->words['transfer_balance']}' title='{$this->lang->words['transfer_balance']}' />&nbsp;		
												<input type='submit' class='input_submit' name='submit' value='{$this->lang->words['transfer_balance']}' />
											</p>
											</form>
										</td>
									</tr>
									") : ("")) . "
								</table>
							</td>							
						</tr>
					</table>";
return $IPBHTML;
}

/* -- myLoan --*/
function myLoan($bank) {
$IPBHTML = "";
$IPBHTML .= "<h3 class='bar' style='padding:3px;margin:0px'>{$bank['b_title']} - {$this->lang->words['loan']} <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=invest&amp;area=single&amp;type=bank&amp;id={$bank['b_id']}&amp;bank_type={$bank['type']}' class='__item __id{$bank['b_id']}__type_bank_{$bank['type']}' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a></h3>
					<table class='ipb_table'>
						<tr>
							<td>
								{$bank['image_thumb_link']}
							</td>
							<td colspan='4'>
								<table class='ipb_table'>
									<tr>
										<td style='width:33%;text-align:left'>
											<img src='{$this->settings['img_url']}/eco_images/money_dollar.png' alt='{$this->lang->words['total_owed']}' /> {$this->lang->words['total_owed']}: {$bank['total_value']} {$this->settings['eco_general_currency']}
										</td>
										<td style='width:1%' >
											&nbsp;
										</td>										
										<td style='width:33%;text-align:center'>
											<img  src='{$this->settings['img_url']}/eco_images/calendar.png' alt='{$this->lang->words['opened_on']}' /> {$this->lang->words['opened_on']}:  {$bank['open_date']}
										</td>
										<td style='width:33%;text-align:right'>
											<img  src='{$this->settings['img_url']}/eco_images/coins_add.png' alt='{$this->lang->words['apy']}' />	{$this->lang->words['apy']}: {$bank['b_loans_fee']}{$this->lang->words['%']}
										</td>										
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td>
								&nbsp;
							</td>						
							<td>
								<strong>{$this->lang->words['due_date']}:</strong> {$bank['value2']}<br />
								<strong>{$this->lang->words['overdue_penalty']}:</strong> {$bank['b_loans_pen']}{$this->lang->words['%']}
							</td>
							<td style='text-align:right'>
								<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=loan_payment' method='post'>
								<input type='hidden' name='item_id' value='{$bank['b_id']}_loan' />
								<p style='padding-bottom:15px;padding-right:10px;'>
									<input type='text' name='amount' value='{$this->lang->words['number_icon']}' onfocus=\"value=''\" size='4' />
								</p>
								<p class='reputation zero'>
									<img style='margin:1px 0px 6px 0px' src='{$this->settings['img_url']}/eco_images/money_add.png' alt='{$this->lang->words['make_payment']}' title='{$this->lang->words['make_payment']}' />&nbsp;		
									<input type='submit' class='input_submit' style='padding:2px 0px 2px 0px' name='submit' value='{$this->lang->words['make_payment']}' />
								</p>
								</form>
							</td>						
						</tr>
					</table>";
return $IPBHTML;
}

/* -- myLT --*/
function myLT($LT) {
$IPBHTML = "";
$IPBHTML .= "<h3 class='bar' style='padding:3px;margin:0px'>{$LT['lt_title']} <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=invest&amp;area=single&amp;type=lt&amp;id={$LT['lt_id']}' class='__item __id{$LT['lt_id']}__type_lt_{$LT['link_type_type']}' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a></h3>
					<table class='ipb_table'>
						<tr>
							<td>
								{$LT['image_thumb_link']}
							</td>
							<td colspan='4'>
								<table class='ipb_table'>
									<tr>
										<td style='width:33%;text-align:left'>
											<img src='{$this->settings['img_url']}/eco_images/money_dollar.png' alt='{$this->lang->words['total_value']}' /> {$this->lang->words['total_value']}: {$LT['total_value']} {$this->settings['eco_general_currency']}
										</td>
										<td style='width:33%;text-align:center'>
											 <img  src='{$this->settings['img_url']}/eco_images/calendar.png' alt='{$this->lang->words['opened_on']}' /> {$this->lang->words['opened_on']}:  {$LT['open_date']}
										</td>										
										<td style='width:11%;text-align:center'>
											 <img  src='{$this->settings['img_url']}/eco_images/stop.png' alt='{$this->lang->words['risk_level']}' /> {$this->lang->words['risk']}: 
										</td>
										<td style='width:22%;text-align:right'>
											<div style='padding:3px'>
											<p style='width:135px' class='progress_bar user_warn'  title='{$this->lang->words['level_of_risk']}: {$LT['lt_risk_level']}%'>
											<span style='width: {$LT['lt_risk_level']}%'><span>{$this->lang->words['risk_level']}: {$LT['lt_risk_level']}%</span></span>
											</p></div>										
										</td>										
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td style='width:5%;'>
								&nbsp;
							</td>						
							<td style='width:40%;'>
								<table class='ipb_table' style='border-bottom:none;'>
									<tr>										
										<td>											
											<strong>{$this->lang->words['type']}:</strong> 
										</td>
										<td>											
											{$LT['lt_type']}
										</td>										
									</tr>								
									<tr>
										<td>							
											<strong>{$this->lang->words['earliest_can_sell']}:</strong> 
										</td>
										<td>
											{$LT['value']}
										</td>
									</tr>
									<tr>
										<td>											
											<strong>{$this->lang->words['early_cash_fee']}:</strong> 
										</td>
										<td>											
											{$LT['lt_early_cash']}
										</td>
									</tr>
								</table>								
							</td>
							<td style='width:20%;'>
								<strong>{$this->lang->words['cashout_fee']}:</strong> {$this->settings['eco_lts_sell_fee']}%
							</td>	
							<td style='text-align:right;width:35%;'>
								<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=sell_lt' method='post'>
								<input type='hidden' name='item_id' value='{$LT['lt_id']}' />
								<p style='padding-bottom:15px;padding-right:10px;'>
									<input type='text' name='amount' value='{$this->lang->words['number_icon']}' onfocus=\"value=''\" size='4' />
								</p>
								<p class='reputation zero'>
									<img style='margin:1px 0px 6px 0px'  src='{$this->settings['img_url']}/eco_images/money_delete.png' alt='{$this->lang->words['cashout']}' title='{$this->lang->words['cashout']}' />&nbsp;		
									<input type='submit' class='input_submit' name='submit' style='padding:2px 0px 2px 0px' value='{$this->lang->words['cashout']}' />
								</p>
								</form>
							</td>							
						</tr>
					</table>";
return $IPBHTML;
}

/* -- myShopItem --*/
function myShopItem($item) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy2', $this->_funcHooks['myShopItem'] ) )
{
$count_3bf65f976dc84174a0f63deb0948d3bd = is_array($this->functionData['myShopItem']) ? count($this->functionData['myShopItem']) : 0;
$this->functionData['myShopItem'][$count_3bf65f976dc84174a0f63deb0948d3bd]['item'] = $item;
}
$IPBHTML .= "<h3 class='bar' style='padding:3px;margin:0px'>{$item['si_title']} ({$item['total_value']}) <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=shop&amp;area=single&amp;type=item&amp;id={$item['si_id']}' class='__item __id{$item['si_id']}__type_shopitem_Item' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a></h3>
					<table class='ipb_table'>
						<tr>
							<td>
								{$item['image_thumb_link']}
							</td>
							<td colspan='3'>
								<table class='ipb_table'>
									<tr>
										<td style='width:33%;text-align:left'>
											<img src='{$this->settings['img_url']}/eco_images/money_dollar.png' alt='{$this->lang->words['current_cost']}' /> {$this->lang->words['current_cost']}: {$this->settings['eco_general_cursymb']}{$item['si_cost']}
										</td>									
										<td style='width:33%;text-align:center'>
											<img  src='{$this->settings['img_url']}/eco_images/calendar.png' alt='{$this->lang->words['next_restock']}' /> {$this->lang->words['next_restock']}:  {$item['si_restock_date']}
										</td>
										<td style='width:33%;text-align:right'>
											<img  src='{$this->settings['img_url']}/eco_images/coins_add.png' alt='{$this->lang->words['item_limit']}' />	{$this->lang->words['item_limit']}: {$item['si_limit']}
										</td>										
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan='4'>
								<table class='ipb_table' style='border-bottom:none'>
									<tr>
										<td colspan='2' style='width:55%'>
											<span style='font-weight: bolder'>{$this->lang->words['description']}:</span>
											<span style='font-size:0.75em;'>{$item['si_desc']}</span><br />
										</td>
										<td style='text-align:right;width:10%'>
											<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=use_shopitem' method='post'>
											<input type='hidden' name='item_id' value='{$item['si_id']}' />
											<p>
												&nbsp;
											</p>
										</td>
										<td style='text-align:right;width:35%'>
											" . (($item['si_file'] != 'blank_unusable_item.php') ? ("	
												<p class='reputation zero'>
													<img src='{$this->settings['img_url']}/eco_images/bullet_go.png' alt='{$this->lang->words['use_item']}' title='{$this->lang->words['use_item']}' />&nbsp;		
													<input type='submit' class='input_submit' name='submit' value='{$this->lang->words['use_item']}' />
												</p>
											") : ("")) . "
											</form>
										</td>
									</tr>
									" . (($item['can_sell']) ? ("								
									<tr>
										<td colspan='2'>
											<span style='font-weight: bolder'>{$this->lang->words['sell_back_fee']}:</span>
											<span style='font-size:0.75em;'>{$this->settings['eco_shop_sell_fee']}{$this->lang->words['%']}</span><br />
										</td>										
										<td style='text-align:right'>											
											<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=sell_shopitem' method='post'>
											<input type='hidden' name='item_id' value='{$item['si_id']}' />
											<p>
												<input type='text' name='amount' value='{$this->lang->words['number_icon']}' onfocus=\"value=''\" size='4' />
											</p>
										</td>
										<td style='text-align:right'>											
											<p class='reputation zero'>
												<img src='{$this->settings['img_url']}/eco_images/cancel.png' alt='{$this->lang->words['sell_back_for_cash']}' title='{$this->lang->words['sell_back_for_cash']}' />&nbsp;		
												<input type='submit' class='input_submit' name='submit' value='{$this->lang->words['sell_back']}' />
											</p>
											</form>
										</td>
									</tr>
									") : ("")) . "
									" . (($item['can_trade']) ? ("									
									<tr>
										<td>
											<span style='font-weight: bolder'>{$this->lang->words['trade_tax']}:</span>
											<span style='font-size:0.75em;'>{$this->settings['eco_shop_trade_tax']}{$this->lang->words['%']}</span><br />
										</td>
										<td>
											<p>
											<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=trade_shopitem' method='post'>
											<input type='hidden' name='item_id' value='{$item['si_id']}' />											
												{$this->lang->words['to']} <input type=\"text\" class='input_text' id='mem_name1' name=\"mem_name\" size=\"10\" value=\"{$mem_name}\" tabindex=\"0\" />
											</p>
										</td>										
										<td style='text-align:right'>
											<p>
												<input type='text' name='amount' value='{$this->lang->words['number_icon']}' onfocus=\"value=''\" size='4' />
											</p>
										</td>
										<td style='text-align:right'>								
											<p class='reputation zero'>
												<img src='{$this->settings['img_url']}/eco_images/group_go.png' alt='{$this->lang->words['send_item']}' title='{$this->lang->words['send_item']}' />&nbsp;		
												<input type='submit' class='input_submit' name='submit' value='{$this->lang->words['send_item']}' />
											</p>
											</form>
										</td>
									</tr>
									") : ("")) . "
								</table>
							</td>							
						</tr>
					</table>	
		<script type=\"text/javascript\">
		document.observe(\"dom:loaded\", function(){
			var url = ipb.vars['base_url'] + 'app=core&module=ajax&section=findnames&do=get-member-names&secure_key=' + ipb.vars['secure_hash'] + '&name=';
			new ipb.Autocomplete( $('mem_name1'), { multibox: false, url: url, templates: { wrap: ipb.templates['autocomplete_wrap'], item: ipb.templates['autocomplete_item'] } } );
		});
		</script>";
return $IPBHTML;
}

/* -- myStock --*/
function myStock($stock) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy2', $this->_funcHooks['myStock'] ) )
{
$count_4f01652a2f0af04f4eab0cf6f3afa212 = is_array($this->functionData['myStock']) ? count($this->functionData['myStock']) : 0;
$this->functionData['myStock'][$count_4f01652a2f0af04f4eab0cf6f3afa212]['stock'] = $stock;
}
$IPBHTML .= "<h3 class='bar' style='padding:3px;margin:0px'>{$stock['s_title']} - {$stock['s_title_long']} ({$stock['num_shares']} {$this->lang->words['shares']}) <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=invest&amp;area=single&amp;type=stock&amp;id={$stock['s_id']}' class='__item __id{$stock['s_id']}__type_stock_{$stock['link_type_type']}' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a></h3>	
					<table class='ipb_table'>
						<tr>
							<td>
								{$stock['image_thumb_link']}
							</td>
							<td colspan='4'>
								<table class='ipb_table'>
									<tr>
										<td style='width:33%;text-align:left''>
											<img src='{$this->settings['img_url']}/eco_images/money_dollar.png' alt='{$this->lang->words['total_value']}' /> {$this->lang->words['total_value']}: {$stock['total_value']} {$this->settings['eco_general_currency']}
										</td>
										<td style='width:33%;text-align:center''>
											 <img  src='{$this->settings['img_url']}/eco_images/calendar.png' alt='{$this->lang->words['opened_on']}' /> {$this->lang->words['opened_on']}:  {$stock['open_date']}
										</td>										
										<td style='width:11%;text-align:center'>
											 <img  src='{$this->settings['img_url']}/eco_images/stop.png' alt='{$this->lang->words['risk_level']}' /> {$this->lang->words['risk']}: 
										</td>
										<td style='width:22%;text-align:right'>
											<div style='padding:3px'>
											<p style='width:135px' class='progress_bar user_warn'  title='{$this->lang->words['level_of_risk']}: {$stock['s_risk_level']}%'>
											<span style='width: {$stock['s_risk_level']}%'><span>{$this->lang->words['risk_level']}: {$stock['s_risk_level']}%</span></span>
											</p></div>										
										</td>										
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td>
								&nbsp;
							</td>						
							<td>
								<table class='ipb_table' style='border-bottom:none;'>
									<tr>
										<td>							
											<strong>{$this->lang->words['type']}:</strong> 
										</td>
										<td>
											{$stock['s_type']}
										</td>
									</tr>
									<tr>
										<td>											
											<strong>{$this->lang->words['variable']}:</strong> 
										</td>
										<td>											
											{$stock['s_type_var']}
										</td>
									</tr>
									<tr>										
										<td>											
											<strong>{$this->lang->words['subject']}:</strong> 
										</td>
										<td>											
											{$stock['s_type_var_value']}
										</td>										
									</tr>
								</table>								
							</td>
							<td>
								<strong>{$this->lang->words['share_value']}:</strong> {$stock['cost']}
								
                          " . (($stock['can_sell']) ? ("						
							<br /><br />
								<strong>{$this->lang->words['sell_fee']}:</strong> {$this->settings['eco_stocks_sell_fee']}%
							</td>	
							<td style='text-align:right'>
								<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=portfolio_update&amp;type=sell_stock' method='post'>
								<input type='hidden' name='item_id' value='{$stock['s_id']}' />
								<p style='padding-bottom:15px;padding-right:10px;'>
									<input type='text' name='amount' value='{$this->lang->words['shares']}' onfocus=\"value=''\" size='6' />
								</p>
								<p class='reputation zero'>
									<img style='margin:1px 0px 6px 0px'  src='{$this->settings['img_url']}/eco_images/money_delete.png' alt='{$this->lang->words['sell_shares']}' title='{$this->lang->words['sell_shares']}' />&nbsp;		
									<input type='submit' class='input_submit' name='submit' style='padding:2px 0px 2px 0px' value='{$this->lang->words['sell_shares']}' />
								</p>
								</form>
							</td>
					      ") : ("
							</td>
                          ")) . "							
						</tr>
					</table>";
return $IPBHTML;
}

/* -- myWelfare --*/
function myWelfare($text) {
$IPBHTML = "";
$IPBHTML .= "<div class='ipsBox'>
	<form method='post' action='{$this->settings['base_url']}app=ibEconomy&amp;do=welfare_payback' onsubmit=\"return confirm('{$this->lang->words['confirm_welfare_payback']}');\">	
		<div class='ipsBox_container ipsPad'>
			<div class='message' style='margin:10px'>
				<img title = '{$this->lang->words['youre_on_welfare']}' src = '{$this->settings['img_url']}/accept.png' /> {$text}<br /><br />
				{$this->lang->words['your_total_welfare_received']}&nbsp;<p class='ipsBadge ipsBadge_red'>" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['eco_welfare'] ) . " {$this->settings['eco_general_currency']}<p>
			</div>
			<ul class='ipsForm ipsForm_vertical'>
				<li class='ipsField'>
					<label class='ipsField_title'>{$this->lang->words['how_much_welfare_payback']} <spanclass='ipsForm_required'>*</span></label>
					<div class='ipsField_content'>
						<input type='text' size='10' name='amount' id='amount' /><br />
					</div>
				</li>				
			</ul>
		</div>
		<fieldset class='submit'>
			<input type='submit' class='input_submit' value='{$this->lang->words['make_payment']}' />
		</fieldset>
	</form>
</div>";
return $IPBHTML;
}

/* -- shop_cats_row --*/
function shop_cats_row($cat) {
$IPBHTML = "";
$IPBHTML .= "<tr id='{$cat['sc_id']}' class='row1'>
				<td class='altrow short'>
					{$cat['image_thumb_link']}
				</td>
				<td>
					<span style='font-weight:bolder'>
						<a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=shop&amp;area=items&amp;cat={$cat['sc_id']}\">{$cat['sc_title']}</a>
					</span>
				</td>
				<td>
					{$cat['sc_desc']}
				</td>				
				<td class='altrow short'>
					{$cat['total_items']}
				</td>
				<td class='short'>
					<a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=shop&amp;area=items&amp;cat={$cat['sc_id']}\"><img src='{$this->settings['img_url']}/eco_images/folder_magnify.png'></a>
				</td>
			</tr>";
return $IPBHTML;
}

/* -- shop_cats_wrapper --*/
function shop_cats_wrapper($content, $pages) {
$IPBHTML = "";
$IPBHTML .= "<div class='maintitle'>{$this->lang->words['categories']}</div>
		<table class='ipb_table'>
			<tr class='header'>
				<th scope='col'>&nbsp;</th>
				<th scope='col'>{$this->lang->words['name']}</th>
				<th scope='col'>{$this->lang->words['description']}</th>
				<th scope='col' class=' short'>{$this->lang->words['item_count']}</th>
				<th scope='col' class=' short'>{$this->lang->words['view_items']}</th>
			</tr>
            {$content}
		</table>
		<div style='margin:10px;'>
			{$pages}
		</div>";
return $IPBHTML;
}

/* -- shop_items_row --*/
function shop_items_row($item='') {
$IPBHTML = "";
$IPBHTML .= "<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=add_to_cart' method='post'>
	<input type='hidden' name='item_id' value='shopitem_{$item['si_id']}' />
		<p class='message'><img src='{$this->settings['img_url']}/information.png' /> {$this->lang->words['description']}: {$item['si_desc']}</p><br />
		<ul class='ipsForm ipsForm_horizontal'>
			<li class='ipsField'>{$this->lang->words['next_restock']}: {$item['si_restock_date']}</li>
			<li class='ipsField'>{$this->lang->words['item_limit']}: {$item['si_limit']}</li><br />	
			<li class='ipsField'>
				<label class='ipsField_title'>{$this->lang->words['num_to_purchase']} <spanclass='ipsForm_required'>*</span></label>
				<div class='ipsField_content'>
					<input type=\"text\" class='input_text' id='quantity' name=\"quantity\" size=\"3\" /><br />
				</div>
			</li>
		</ul>
	<fieldset class='submit'>
		<input type='submit' class='input_submit' value='{$this->lang->words['add_to_cart']}' />
	</fieldset>
	</form>";
return $IPBHTML;
}

/* -- shop_items_wrapper --*/
function shop_items_wrapper($content='', $pages='') {
$IPBHTML = "";
$IPBHTML .= "<fieldset style='margin: 0px;padding:0px;'>
				<div id='member_list' class='clear block_wrap' style='padding:0px;margin:0px;'>
					<div id='member_wrap' >
						<ul class='members' >		
							{$content}
						</ul>
					</div>
				</div>
				<div style='margin:10px;'>
					{$pages}
				</div>
		</fieldset>";
return $IPBHTML;
}

/* -- showBankCard --*/
function showBankCard($bank='') {
$IPBHTML = "";
$IPBHTML .= "<div class='vcard userpopup'>
	<h3><a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=invest&amp;area=single&amp;type=bank&amp;id={$bank['b_id']}&amp;bank_type={$bank['type']}\">{$bank['b_title']} - {$bank['langed_type']}</a></h3>	
	<div class='side left ipsPad'>
		{$bank['image_link_popup']}<br />
		<div class='reputation zero'>
			<span class='number'><img src='{$this->settings['img_url']}/eco_images/money_dollar.png' /><span style='font-weight:bolder;font-size:1.3em'>{$this->registry->ecoclass->truncate($bank['funds'], 10)}</span>
		</div>
	</div>
	<div class='ipsPad'>
		<p class='message user_status'>{$this->registry->ecoclass->truncate($bank['desc'], 100)}</p>
		<div class='info'>			
			<dl>
			" . (($bank['type'] != 'Loan') ? ("
				<dt>{$this->lang->words['cost']}</dt>
				<dd>{$bank['cost']}</dd>
				<dt>{$this->lang->words['dep_fee']}</dt>
				<dd>{$bank['dep_fee']}</dd>
				<dt>{$this->lang->words['wth_fee']}</dt>
				<dd>{$bank['wth_fee']}</dd>
				<dt>{$this->lang->words['apy']}</dt>
				<dd>{$bank['apy']}</dd>
			") : ("
				<dt>{$this->lang->words['max_loan_short']}</dt>
				<dd>{$this->settings['eco_general_cursymb']}{$bank['b_loans_max']}</dd>
				<dt>{$this->lang->words['loan_fee']}</dt>
				<dd>{$bank['b_loans_fee']}{$this->lang->words['%']}</dd>
				<dt>{$this->lang->words['loan_time']}</dt>
				<dd>{$bank['b_loans_days']} {$this->lang->words['days']}</dd>
				<dt>{$this->lang->words['overdue_penalty_short']}</dt>
				<dd>{$bank['b_loans_pen']}{$this->lang->words['%']}</dd>		
			")) . "
			</dl>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- showCCCard --*/
function showCCCard($cc='') {
$IPBHTML = "";
$IPBHTML .= "<div class='vcard userpopup'>
	<h3><a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=invest&amp;area=single&amp;type=cc&amp;id={$cc['cc_id']}\">{$cc['cc_title']}</a> (<span style='font-size:0.95em;' title='{$this->lang->words['credit_line']}'>{$this->settings['eco_general_cursymb']}{$cc['credit_line']}</span>)</h3>	
	<div class='side left ipsPad'>
		{$cc['image_link_popup']}<br />
		<div class='reputation zero'>
			<span class='number'><img src='{$this->settings['img_url']}/eco_images/money_dollar.png' /><span style='font-weight:bolder;font-size:1.3em'>{$this->registry->ecoclass->truncate($cc['funds'], 10)}</span>
		</div>
	</div>
	<div class='ipsPad'>
		<p class='message user_status'>{$this->registry->ecoclass->truncate($cc['desc'], 100)}</p>
		<div class='info'>			
			<dl>
				<dt>{$this->lang->words['cost']}</dt>
				<dd>{$cc['cost']}</dd>
				<dt>{$this->lang->words['apr']}</dt>
				<dd>{$cc['apr']}</dd>
				<dt>{$this->lang->words['csh_adv_fee_short']}</dt>
				<dd>{$cc['cc_csh_adv_fee']}</dd>
				<dt>{$this->lang->words['bal_transfer_apr_short']}</dt>
				<dd>{$cc['cc_bal_trnsfr_apr']}</dd>
			</dl>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- showLotteryCard --*/
function showLotteryCard($lotto='') {
$IPBHTML = "";
$IPBHTML .= "<div class='vcard userpopup'>
	<h3><a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=cash&amp;area=single&amp;type=lottery&amp;id={$lotto['l_id']}\">{$lotto['l_draw_date']}</a></h3>	
	<div class='side left ipsPad'>
		{$lotto['image_link_popup']}<br />
		<div class='reputation zero'>
			<span class='number'><img src='{$this->settings['img_url']}/eco_images/money_dollar.png' /><span style='font-weight:bolder;font-size:1.3em'>{$this->registry->ecoclass->truncate($lotto['l_final_pot_size'], 10)}</span>
		</div>
	</div>
	<div class='ipsPad'>
		<p class='message user_status'>{$this->lang->words['lotto_description']}</p>
		<div class='info'>			
			<dl>
				<dt>{$this->lang->words['ticket_price']}</dt>
				<dd >{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_lotto_ticket_price'], $this->registry->ecoclass->decimal ) . "</dd>
				<dt>{$this->lang->words['your_tickets']}</dt>
				<dd>{$lotto['your_num_total_tix']}</dd>
				<dt>{$this->lang->words['winner']}</dt>
				<dd>{$lotto['winner_link']}</dd>
				<dt>{$this->lang->words['total_sold']}</dt>
				<dd>{$lotto['l_tix_purchased']}</dd>
			</dl>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- showLTCard --*/
function showLTCard($lt='') {
$IPBHTML = "";
$IPBHTML .= "<div class='vcard userpopup'>
	<h3><a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=invest&amp;area=single&amp;type=lt&amp;id={$lt['lt_id']}\">{$lt['lt_title']}</a></h3>	
	<div class='side left ipsPad'>
		{$lt['image_link_popup']}<br />
		<div class='reputation zero'>
			<span class='number'><img src='{$this->settings['img_url']}/eco_images/money_dollar.png' /><span style='font-weight:bolder;font-size:1.3em'>{$this->registry->ecoclass->truncate($lt['funds'], 10)}</span>
		</div>
	</div>
	<div class='ipsPad'>
		<p class='message user_status'>{$this->registry->ecoclass->truncate($lt['desc'], 100)}</p>
		<div class='info'>			
			<dl>
				<dt>{$this->lang->words['type']}</dt>
				<dd >{$lt['lt_type']}</dd>
				<dt>{$this->lang->words['min_investment_short']}</dt>
				<dd> {$this->settings['eco_general_cursymb']}{$lt['min_invest']}</dd>
				<dt>{$this->lang->words['min_invest_time_short']}</dt>
				<dd>{$lt['min_days']} {$this->lang->words['days']}</dd>
				<dt>{$this->lang->words['early_cash_fee_short']}</dt>
				<dd>{$lt['lt_early_cash']}</dd>	
				<dt>{$this->lang->words['risk']}</dt>
				<dd>{$lt['lt_risk_level']}{$this->lang->words['%']}</dd>					
			</dl>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- showShopItemCard --*/
function showShopItemCard($item='') {
$IPBHTML = "";
$IPBHTML .= "<div class='vcard userpopup'>
	<h3><a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=shop&amp;area=single&amp;type=shopitem&amp;id={$item['si_id']}\">{$item['si_title']}</a></h3>	
	<div class='side left ipsPad'>
		{$item['image_link_popup']}<br />
		<div class='reputation zero'>
			<span class='number'><img src='{$this->settings['img_url']}/eco_images/money_dollar.png' /><span style='font-weight:bolder;font-size:1.3em'>{$this->registry->ecoclass->truncate($item['si_cost'], 10)}</span>
		</div>
	</div>
	<div class='ipsPad'>
			<p class='message user_status'>{$item['si_desc']}</p>
		<div class='info'>			
			<dl>
				<dt>{$this->lang->words['current_inventory']}</dt>
				<dd >{$item['si_inventory']}</dd>
				<dt>{$this->lang->words['next_restock']}</dt>
				<dd>{$item['si_restock_date']}</dd>
				<dt>{$this->lang->words['item_limit']}</dt>
				<dd>{$item['si_limit']}</dd>
				<dt>{$this->lang->words['total_sold']}</dt>
				<dd>{$item['si_sold']}</dd>
			</dl>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- showStockCard --*/
function showStockCard($stock='') {
$IPBHTML = "";
$IPBHTML .= "<div class='vcard userpopup'>
	<h3><a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=invest&amp;area=single&amp;type=stock&amp;id={$stock['s_id']}\">{$stock['s_title']} - {$stock['s_title_long']}</a></h3>	
	<div class='side left ipsPad'>
		{$stock['image_link_popup']}<br />
		<div class='reputation zero'>
			<span class='number'><img src='{$this->settings['img_url']}/eco_images/money_dollar.png' /><span style='font-weight:bolder;font-size:1.3em'>{$this->registry->ecoclass->truncate($stock['s_value'], 10)}</span>
		</div>
	</div>
	<div class='ipsPad'>
		<p class='message user_status'>{$this->registry->ecoclass->truncate($stock['desc'], 100)}</p>
		<div class='info'>			
			<dl>
				<dt>{$this->lang->words['type']}</dt>
				<dd >{$stock['s_type']}</dd>
				<dt>{$this->lang->words['variable']}</dt>
				<dd>{$stock['s_type_var']}</dd>
				<dt>{$this->lang->words['subject']}</dt>
				<dd>{$stock['s_type_var_value']}</dd>
				<dt>{$this->lang->words['risk']}</dt>
				<dd>{$stock['s_risk_level']}{$this->lang->words['%']}</dd>
			</dl>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- stock_row --*/
function stock_row($stock='') {
$IPBHTML = "";
$IPBHTML .= "<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=add_to_cart' method='post'>
	<input type='hidden' name='item_id' value='stock_{$stock['s_id']}' />
		<p class='message'><img src='{$this->settings['img_url']}/information.png' /> {$this->lang->words['description']}: {$stock['desc']}<br /><br />
			<i>{$this->lang->words['risk']}:</i> <strong>{$stock['s_risk_level']}%</strong> - {$this->lang->words['risk_reward_exp']}<br /></p><br />
		<ul class='ipsForm ipsForm_horizontal'>
			<li class='ipsField'>{$this->lang->words['level_of_risk']}: <p style='margin-top:-11px;width:135px' class='progress_bar user_warn'  title='{$this->lang->words['level_of_risk']}: {$stock['s_risk_level']}%'>
								<span style='width: {$stock['s_risk_level']}%'><span>{$this->lang->words['risk_level']}: {$stock['s_risk_level']}%</span></span></li>
			<li class='ipsField'>
				<label class='ipsField_title'>{$this->lang->words['number_shares']} <spanclass='ipsForm_required'>*</span></label>
				<div class='ipsField_content'>
					<input type=\"text\" class='input_text' id='quantity' name=\"quantity\" size=\"3\" /><br />
				</div>
			</li>
		</ul>
	<fieldset class='submit'>
		<input type='submit' class='input_submit' value='{$this->lang->words['add_to_cart']}' />
	</fieldset>
	</form>";
return $IPBHTML;
}

/* -- usingItem --*/
function usingItem($item) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy2', $this->_funcHooks['usingItem'] ) )
{
$count_3a48df8604f2d0da39fa7b83fe01dfdb = is_array($this->functionData['usingItem']) ? count($this->functionData['usingItem']) : 0;
$this->functionData['usingItem'][$count_3a48df8604f2d0da39fa7b83fe01dfdb]['item'] = $item;
}
$IPBHTML .= "<div class='maintitle'>{$this->lang->words['using_item']}</div>
<h3 class='bar' style='padding:3px;margin:0px'>{$item['si_title']} <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=shop&amp;area=single&amp;type=item&amp;id={$item['si_id']}' class='__item __id{$item['si_id']}__type_shopitem_Item' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a></h3>
<form method='post' enctype=\"multipart/form-data\" action='{$this->settings['base_url']}app=ibEconomy&amp;tab=me&amp;area=using_shopitem&amp;when=now' onsubmit=\"return confirm('{$this->lang->words['confirm_item_use']}');\">
	<input type='hidden' name='do' value='save' />
	<input type='hidden' name='secure_hash' value='{$this->member->form_hash}' />
	<input type='hidden' name='id' value='{$item['si_id']}' />
	<table class='ipb_table'>
	<tr>
		<td colspan='2'>
			<div class='message' style='margin:10px'>
				{$this->lang->words['item']} {$this->lang->words['description']}: {$item['si_desc']}
			</div>
		</td>
	</tr>						
	" . ((is_array( $item['html'] ) AND count( $item['html'] )) ? ("
		".$this->__f__fd9bc61ec23f13eef478daad053408de($item)."	") : ("")) . "
	</table>
	<fieldset class='submit'>
		<input type='submit' class='input_submit' value='{$this->lang->words['use_item']}' />
	</fieldset>	
</form>

<script type=\"text/javascript\">
document.observe(\"dom:loaded\", function(){
	var url = ipb.vars['base_url'] + 'app=core&module=ajax&section=findnames&do=get-member-names&secure_key=' + ipb.vars['secure_hash'] + '&name=';
	new ipb.Autocomplete( $('mem_name1'), { multibox: false, url: url, templates: { wrap: ipb.templates['autocomplete_wrap'], item: ipb.templates['autocomplete_item'] } } );
});
</script>";
return $IPBHTML;
}


function __f__fd9bc61ec23f13eef478daad053408de($item)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $item['html'] as $itemHtml )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<tr>
				" . (($itemHtml['text'] && $itemHtml['inputs']) ? ("
					<td style='text-align:left;font-weight:bold;padding-left:20px;'>
						{$itemHtml['text']}
					</td>
					<td>
						{$itemHtml['inputs']}
					</td>
				") : ("<td colspan='2'>
						" . (($itemHtml['text']) ? ("{$itemHtml['text']}") : ("{$itemHtml['inputs']}")) . "
					</td>")) . "
			</tr>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- welfareApply --*/
function welfareApply($text) {
$IPBHTML = "";
$IPBHTML .= "<div class='ipsBox'>
	<form method='post' action='{$this->settings['base_url']}app=ibEconomy&amp;do=welfare_signup' onsubmit=\"return confirm('{$this->lang->words['confirm_welfare_signup']}');\">		
		<div class='ipsBox_container ipsPad'>
			<div class='message' style='margin:10px'>
				<img title = '{$this->lang->words['youre_not_on_welfare']}' src = '{$this->settings['img_url']}/cross.png' /> {$text}
			</div><br />
			<ul class='ipsForm ipsForm_vertical'>
				<li class='ipsField'>
					<label class='ipsField_title'>{$this->lang->words['sign_name_for_welfare']} <spanclass='ipsForm_required'>*</span></label><br /><br />
					<div class='ipsField_content'>
						<input type='text' size='20' name='signature' id='signature' /><br />
					</div>
				</li>				
			</ul>
		</div>
		<fieldset class='submit'>
			<input type='submit' class='input_submit' value='{$this->lang->words['sign_up']}' />
		</fieldset>
	</form>
</div>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>