<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 0               */
/* CACHE FILE: Generated: Tue, 04 Aug 2009 19:56:24 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_stats_0 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- group_strip --*/
function group_strip($group="", $members=array()) {
$IPBHTML = "";

$this->registry->templateStriping['staff'] = array( FALSE, "row1","row2");
$IPBHTML .= "<!-- This is looped over once for admins, once for supmods, and then once for forum mods -->
<table class='ipb_table'>
	<caption class='maintitle'>{$group}</caption>
	<tr class='header'>
		<th scope='col' style='width: 3%'>&nbsp;</th>
		<th scope='col' style='width: 25%'>{$this->lang->words['leader_name']}</th>
		<th scope='col' style='width: 35%' class='short'>{$this->lang->words['leader_forums']}</th>
		<th scope='col' style='width: 25%'>{$this->lang->words['leader_location']}</th>
		<th scope='col' style='width: 12%'>&nbsp;</th>
	</tr>
	" . ((count($members) AND is_array($members)) ? ("
				".$this->__f__9319fd58e603cd74f90d8ff74fa5c658($group,$members)."	") : ("")) . "
</table>
<br />";
return $IPBHTML;
}


function __f__1b1bcb9c360ca7b7413d654756a39bf9($group="", $members=array(),$info='')
{
	$_ips___x_retval = '';
	foreach( $info['forums'] as $id => $name )
	{
		
		$_ips___x_retval .= "
									<option value=\"{$id}\">{$name}</option>
								
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__9319fd58e603cd74f90d8ff74fa5c658($group="", $members=array())
{
	$_ips___x_retval = '';
	foreach( $members as $info )
	{
		
		$_ips___x_retval .= "
			<tr class='" .  IPSLib::next( $this->registry->templateStriping["staff"] ) . "'>
				<td>
					<img src='{$info['pp_mini_photo']}' alt='photo' class='photo' width='{$info['pp_mini_width']}' height='{$info['pp_mini_height']}' />
				</td>
				<td>
					" . (($info['member_id'] > 0) ? ("
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$info['member_id']}", 'public','' ), "{$info['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$info['members_display_name']}</a> " . $this->registry->getClass('output')->getTemplate('global')->user_popup($info['member_id'],$info['members_display_name']) . "
					") : ("
						{$info['members_display_name']}
					")) . "
				</td>
				<td class='altrow short'>
					" . ((is_array($info['forums'])) ? ("
						<form method=\"post\" action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", 'public','' ), "", "" ) . "\" id=\"jmenu{$info['member_id']}\" class='jump'>
							<select name=\"showforum\">
								<option value=\"-1\">" . sprintf($this->lang->words['no_forums'],count($info['forums'])) . "</option>
								<option value=\"-1\">---------------------------</option>
								".$this->__f__1b1bcb9c360ca7b7413d654756a39bf9($group,$members,$info)."							</select>
							<input type='submit' class='input_submit alt' value='{$this->lang->words['go_button']}' />
						</form>
					") : ("
						{$info['forums']}
					")) . "
				</td>
				<td>
					{$info['online_extra']}
				</td>
				<td class='short altrow'>
					<ul class='user_controls clear'>
						" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $info['member_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("" . ((IPSMember::checkFriendStatus( $info['member_id'] )) ? ("
								<li class='mini_friend_toggle is_friend' id='friend_xxx_{$info['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id={$info['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a></li>
							") : ("
								<li class='mini_friend_toggle is_not_friend' id='friend_xxx_{$info['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id={$info['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a></li>								
							")) . "") : ("")) . "
						" . (($this->memberData['g_use_pm'] AND $this->memberData['member_id'] != $info['member_id'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' )) ? ("
							<li class='pm_button' id='pm_xxx_{$info['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$info['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['pm_member']}'>" . $this->registry->getClass('output')->getReplacement("send_msg") . "</a></li>
						") : ("")) . "
						" . (($info['has_blog'] AND IPSLib::appIsInstalled( 'blog' )) ? ("
							<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;mid={$info['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_blog']}'>" . $this->registry->getClass('output')->getReplacement("blog_link") . "</a></li>
						") : ("")) . "
						" . (($info['has_gallery'] AND IPSLib::appIsInstalled( 'gallery' )) ? ("
							<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=user&amp;section=user&amp;user={$info['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_gallery']}'>" . $this->registry->getClass('output')->getReplacement("gallery_link") . "</a></li>
						") : ("")) . "
					</ul>
				</td>
			</tr>
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- top_posters --*/
function top_posters($rows) {
$IPBHTML = "";

$this->registry->templateStriping['top_posters'] = array( FALSE, "row1","row2");
$IPBHTML .= "<table class='ipb_table'>
	<caption class='maintitle'>{$this->lang->words['todays_posters']}</caption>
	<tr class='header'>
		<th scope='col' style='width: 3%'>&nbsp;</th>
		<th scope='col'>{$this->lang->words['member']}</th>
		<th scope='col'>{$this->lang->words['member_joined']}</th>
		<th scope='col' class='short'>{$this->lang->words['member_posts']}</th>
		<th scope='col' class='short'>{$this->lang->words['member_today']}</th>
		<th scope='col' class='short'>{$this->lang->words['member_percent']}</th>
		<th scope='col' class='short'>&nbsp;</th>
	</tr>
	" . ((!is_array($rows) OR !count($rows)) ? ("
		<tr>
			<td colspan='7' class='no_messages'>{$this->lang->words['no_info']}</td>
		</tr>
	") : ("
				".$this->__f__6dd9f5a71e61b34c28ffb19cd0f7a759($rows)."	")) . "
</table>";
return $IPBHTML;
}


function __f__6dd9f5a71e61b34c28ffb19cd0f7a759($rows)
{
	$_ips___x_retval = '';
	foreach( $rows as $info )
	{
		
		$_ips___x_retval .= "
			<tr class='" .  IPSLib::next( $this->registry->templateStriping["top_posters"] ) . "'>
				<td>
					<img src='{$info['pp_mini_photo']}' alt=\"{$info['members_display_name']}{$this->lang->words['users_photo']}\" class='photo' width='{$info['pp_mini_width']}' height='{$info['pp_mini_height']}' />
				</td>
				<td>
					" . (($info['member_id'] > 0) ? ("
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$info['member_id']}", 'public','' ), "{$info['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$info['members_display_name']}</a> " . $this->registry->getClass('output')->getTemplate('global')->user_popup($info['member_id'], $info['members_display_name']) . "
					") : ("
						{$info['members_display_name']}
					")) . "
				</td>
				<td class='altrow'>
					" . $this->registry->getClass('class_localization')->getDate($info['joined'],"joined", 0) . "
				</td>
				<td class='short'>
					" . $this->registry->getClass('class_localization')->formatNumber( $info['posts'] ) . "
				</td>
				<td class='altrow short'>
					" . $this->registry->getClass('class_localization')->formatNumber( $info['tpost'] ) . "
				</td>
				<td class='short'>
					{$info['today_pct']}%
				</td>
				<td class='altrow short'>
					<ul class='user_controls clear'>
						" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $info['member_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("" . ((IPSMember::checkFriendStatus( $info['member_id'] )) ? ("
								<li class='mini_friend_toggle is_friend' id='friend_xxx_{$info['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id={$info['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a></li>
							") : ("
								<li class='mini_friend_toggle is_not_friend' id='friend_xxx_{$info['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id={$info['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a></li>								
							")) . "") : ("")) . "
						" . (($this->memberData['g_use_pm'] AND $this->memberData['member_id'] != $info['member_id'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' )) ? ("
							<li class='pm_button' id='pm_xxx_{$info['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$info['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['pm_member']}'>" . $this->registry->getClass('output')->getReplacement("send_msg") . "</a></li>
						") : ("")) . "
						" . (($info['has_blog'] AND IPSLib::appIsInstalled( 'blog' )) ? ("
							<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;mid={$info['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_blog']}'>" . $this->registry->getClass('output')->getReplacement("blog_link") . "</a></li>
						") : ("")) . "
						" . (($info['has_gallery'] AND IPSLib::appIsInstalled( 'gallery' )) ? ("
							<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=user&amp;section=user&amp;user={$info['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_gallery']}'>" . $this->registry->getClass('output')->getReplacement("gallery_link") . "</a></li>
						") : ("")) . "
					</ul>
				</td>
			</tr>
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- whoPosted --*/
function whoPosted($tid=0, $title="", $rows=array()) {
$IPBHTML = "";

$this->registry->templateStriping['whoposted'] = array( FALSE, "row1","row2");
$IPBHTML .= "" . (($this->request['module']=='ajax') ? ("
	<h3>{$this->lang->words['who_farted']} {$title}</h3>
") : ("
	<h3 class='maintitle'>{$this->lang->words['who_farted']} {$title}</h3>
")) . "
<table class='ipb_table'>
	<tr class='header'>
		<th>{$this->lang->words['whoposted_name']}</th>
		<th>{$this->lang->words['whoposted_posts']}</th>
	</tr>
	" . ((count($rows) AND is_array($rows)) ? ("
				".$this->__f__9b48f78008a9d3866ab8efa69787155c($tid,$title,$rows)."	") : ("")) . "
	</table>";
return $IPBHTML;
}


function __f__9b48f78008a9d3866ab8efa69787155c($tid=0, $title="", $rows=array())
{
	$_ips___x_retval = '';
	foreach( $rows as $row )
	{
		
		$_ips___x_retval .= "
			<tr class='" .  IPSLib::next( $this->registry->templateStriping["whoposted"] ) . "'>
				<td class=\"altrow\">
					" . (($row['author_id']) ? ("
						<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$row['author_id']}", 'public','' ), "{$row['members_seo_name']}", "showuser" ) . "\" title=\"{$this->lang->words['goto_profile']}\">{$row['author_name']}</a>
					") : ("
						{$row['author_name']}
					")) . "
				</td>
				<td>{$row['pcount']}</td>
			</tr>
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- whoPostedAjaxWrapper --*/
function whoPostedAjaxWrapper($output) {
$IPBHTML = "";
$IPBHTML .= "{$output}";
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>