<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 05 Aug 2011 17:35:02 +0000 by cduerr
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'addonchat_err_noperm' => "You are not permitted to enter this chat room.",
'addonchat_title' => "Chat Room",
'addonchat_wcb_title' => "User(s) active in chat room",
'addonchat_wcb_title_paren' => "(in the past 5 minutes)",
 ); 
