<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 16               */
/* CACHE FILE: Generated: Thu, 13 Dec 2012 15:52:42 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_portal_16 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- affiliates --*/
function affiliates($links="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- articles --*/
function articles($articles) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- latestPosts --*/
function latestPosts($posts=array()) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- onlineUsers --*/
function onlineUsers($active) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- pollWrapper --*/
function pollWrapper($content="",$tid="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- siteNavigation --*/
function siteNavigation($links=array()) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- skeletonTemplate --*/
function skeletonTemplate() {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>