<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 16               */
/* CACHE FILE: Generated: Thu, 13 Dec 2012 15:52:42 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_chatpara_16 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- chat_inline --*/
function chat_inline($server="",$group="",$room="",$w="",$h="",$lang="",$textmode="",$style="") {
$IPBHTML = "";
$IPBHTML .= "<script type=\"text/javascript\">
//<![CDATA[
<!-- // Hide JS from HTML validator
// Added like this to allow those without JS to still function nicely.
var chat_display = \"{$this->settings['chat04_display']}\";
var chat_pad     = parseInt( \"{$this->settings['chat04_poppad']}\" );
var chat_height  = parseInt( \"{$this->settings['chat04_height']}\" );
var chat_width   = parseInt( \"{$this->settings['chat04_width']}\" );
var popped       = parseInt( \"{$this->request['pop']}\" );
var chat_tol;
var chat_tol_time = 60 * 1000; // 60 seconds
chat_pad     = chat_pad ? chat_pad : 50;
chat_height += chat_pad;
chat_width  += chat_pad;
if ( chat_display != 'self' && popped != 1 )
{
	if ( window.open( ipb_var_base_url + 'autocom=chatpara&pop=1','Chat','width='+chat_width+',height='+chat_height+',resizable=yes,scrollbars=yes') )
	{
		// Bounce back to board index
		locationjump();
	}
}
//]]>
//-->
</script>
<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$this->lang->words['chat_title']}</div>
	<div class=\"tablepad\" align=\"center\">
	 <div style='border:8px outset #BCD0ED;width:{$w}px;' id=\"chatwrap\">
		<applet codebase=\"$server\" archive=\"pchat.zip\" code=\"ParaChat.class\" width=\"$w\" height=\"$h\"> 
			<param name=cabbase value=\"pchat.cab\"> 
			<param name=roam.Group value=\"$group\"> 
			<param name=Channel value=\"$room\">
			<param name=\"ctrl.Language\" value=\"$lang\">
			<param name=\"ui.ChatWindow\" value=\"$textmode\">
			<param name=\"ui.BgColor\"   value=\"{$style['applet_bg']}\">
			<param name=\"ui.FgColor\"   value=\"{$style['applet_fg']}\">
			<param name=\"cmd.ChatBg\"   value=\"{$style['window_bg']}\">
			<param name=\"cmd.ChatFg\"   value=\"{$style['window_fg']}\">
			<param name=\"cmd.FontSize\" value=\"{$style['font_size']}\">
			<!--CUSTOMPARAM-->
			<!--AUTOLOGIN-->
			{$this->lang->words['para_error_java_start']} <a href=\"http://chathelp.invisionsitetools.com/java.html\">{$this->lang->words['para_err_java_end']}</a>
		</applet>
	  </div>
	</div>
</div>
<br />
<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$this->lang->words['chat_help']}</div>
	<div class=\"tablepad\">
		{$this->lang->words['chat_help_text']}
	</div>
</div>
<script type=\"text/javascript\">
//<![CDATA[
// Set timeout loop to update session's table.
if ( use_enhanced_js )
{
	chat_ping_session();
}
function chat_ping_session()
{
	do_request_function = function()
	{
		if ( ! xmlobj.readystate_ready_and_ok() )
		{
			return;
		}
		
		var returned = xmlobj.xmlhandler.responseText;
		
		if ( returned == 'ok' )
		{
			chat_tol = setTimeout( 'chat_ping_session()', chat_tol_time );
		}
	}
	
	xmlobj = new ajax_request();
	xmlobj.onreadystatechange( do_request_function );
	xmlobj.process( ipb_var_base_url + 'autocom=chatpara&do=update' );
}
//]]>
</script>";
return $IPBHTML;
}

/* -- chat_inline_v7 --*/
function chat_inline_v7($server="",$siteid="",$w="",$h="", $room='') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- current --*/
function current($options) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- legacy --*/
function legacy($options) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>