<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 21 Mar 2012 13:12:18 +0000 by penguin
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'c_addcal' => "Add New Calendar",
'c_added' => "New Calendar Added",
'c_block_bday' => "<strong>Calendar: Birthday Limit</strong>",
'c_block_bday_info' => "This is the number of birthdays listed per day before they are replaced by a single link<br />Enter 0 to not show birthdays at all",
'c_block_enable' => "<strong>RSS: Enable</strong>",
'c_block_enable_info' => "If enabled, all <em>n</em> forthcoming events (based on GMT time) that have guest read permission will be exported",
'c_block_forthcoming' => "<strong>RSS: Forthcoming Days</strong>",
'c_block_freq' => "<strong>RSS: Update Frequency</strong>",
'c_block_freq_info' => "The number of minutes between RSS cache rebuilding",
'c_block_limit' => "<strong>Calendar: Event Limit</strong>",
'c_block_limit_info' => "This is the number of events listed per day before they are replaced by a single link to the day's events",
'c_block_max' => "<strong>RSS: Export Maximum Events</strong>",
'c_block_max_info' => "The maximum number of events exported",
'c_block_mod' => "<strong>Calendar: Enable Moderation</strong>",
'c_block_mod_info' => "If enabled, all groups which are not included in the 'Avoid Moderation Queue' will have their events entered into the moderation queue for approval.",
'c_block_rss' => "<strong>RSS Options</strong>",
'c_block_title' => "<strong>Calendar: Title</strong>",
'c_calendars' => "Calendars",
'c_completeform' => "You must complete the entire form.",
'c_deletecal' => "Delete Calendar...",
'c_editbutton' => "Edit Calendar ",
'c_editcal' => "Edit Calendar...",
'c_edited' => "Calendar Edited",
'c_fromcolon' => "From:",
'c_noid' => "No ID was passed. Please try again.",
'c_options' => "Options",
'c_ranged' => "Ranged Event",
'c_rebuildcal' => "Rebuild Calendar RSS Export...",
'c_recachecal' => "Recache Calendar Events",
'c_recached' => "Calendar Events Recached",
'c_recurring' => "Recurrent Event",
'c_removed' => "Calendar Removed",
'c_rssrecached' => "Calendar Events RSS Recached",
'c_savebutton' => "Save Changes",
'c_singleday' => "Single Day Event On:",
'c_title' => "Calendar Manager",
'c_tocolon' => "To:",
'perm_calendar_nomod' => "Bypass Moderation",
'perm_calendar_start' => "Create Events",
'perm_calendar_view' => "Show Calendar",
 ); 
