<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 21 Mar 2012 13:12:18 +0000 by penguin
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'adding_block' => "Adding New Custom Sidebar Block",
'add_block' => "Add Block",
'add_new_block' => "Add New Block",
'blocks_page' => "Manage Custom Sidebar Blocks",
'blocks_recached' => "Blocks Recached!",
'block_added' => "Block Added!",
'block_deleted' => "Block Deleted!",
'block_details' => "Block Details",
'block_edited' => "<%NAME%> Block Edited!",
'block_title' => "Block Title",
'boxed' => "Boxed",
'custom_sidebar_blocks' => "Custom Sidebar Blocks",
'delete_block' => "Delete Block",
'display_content' => "Display Content",
'do_raw_html' => "Enable RAW HTML/JS mode",
'do_raw_html_exp' => "If enbled, NO PARSING will occur.  Good if you want to show html/javascript only, such as an embeded widget or a banner.",
'editing' => "Editing",
'edit_block' => "Edit Block",
'enabled' => "Enabled",
'enabled_exp' => "Leave off to not show currently.",
'enter_content_below' => "Enter Content to Display Below",
'enter_content_below_exp' => "HTML and BBCODE are OK!",
'error_none_found' => "No blocks found by that ID!",
'error_no_id' => "No ID Provided!",
'general_config' => "General Configuration",
'image' => "Image",
'image_name' => "Full Image Name (with extension).",
'image_name_exp' => "Works with any image in the .public/style_images/master directory.  You can also use an image from within a subdirectory in master, E.G. <i>new images/my_image.png</i> as long as that directory is in the style_images/master folder.",
'options' => "Options",
'perms' => "Permissions",
'recache_blocks' => "Recache Blocks",
'title_exp' => "Displays in the block header.",
'use_box' => "Use Table/Border/Title/Image",
'use_box_exp' => "Leave off to simply show the content with no surrounding html.",
'use_perms' => "Use Permission Matrix Below",
'use_perms_exp' => "Leave at no to disregard below settings",
 ); 
