<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Thu, 13 Dec 2012 15:51:29 +0000 by Walter White
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'memchangeavatar' => "Change Avatar",
'mem_change_button' => "Change...",
'mem_posts' => "Posts",
'mem_remove_avatar' => "Remove Avatar",
'm_overrride' => "Override group permission masks with...",
'strong_avatar_label' => "Avatar",
 ); 
