<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Thu, 13 Dec 2012 15:51:29 +0000 by Walter White
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'publicArticleCommenting' => "Used for the JSON data returned for commenting system.",
 ); 
