<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 21 Mar 2012 13:12:18 +0000 by penguin
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'error_no_dir' => "The directory '{app_name}/extensions/portalPlugins' does not exist. Create it and try again.",
'error_no_key' => "There is no matching plug-in for the key used to find it.",
'main_title' => "Manage Portal Plug-ins",
'plugin_settings' => "Plugin Settings",
'portal_main_key' => "Plug-in Title",
'portal_main_title' => "Portal Plug-ins",
'portal_pop_desc' => "Tag Description",
'portal_pop_name' => "Tag Name",
'portal_pop_tags' => "Exportable Tags:",
'portal_settings' => "Portal Settings",
'view_template_tag' => "View Template Tag",
 ); 
