<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 21 Mar 2012 13:12:18 +0000 by penguin
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'apiCallsReset' => "Reset",
'authorizedRedirect' => "You've authorized this application to communicating with Twitter. Redirecting you back to the board index.",
'authorizeLink' => "You've not authorized this application to communicate with your Twitter account. <a href='%s'>Click here to do so.</a><br />Or <a href='%s'>here</a> to hide this widget.",
'errorInvalidID' => "The status ID you chose to favorite is invalid",
'errorNoReplies' => "No one has replied to you",
'errorNoResults' => "Unfortunately your search didn't return any results.<br />Try broadening the search parameters by searching by different keywords or altering the format of your search.",
'errorNoStatus' => "Tweeting blanks? Come on! Give me a break",
'errorNoTweets' => "None of the guys you're following has posted a tweet yet",
'errorNoUpdates' => "This user hasn't made any updates. Wonder how you found him in the first place...",
'errorSearchQuery' => "You've not specified a search keyword",
'errorTwitterTrouble' => "Twitter is either down for maintenance, or experiencing technical issues",
'favorite' => "favorite this update",
'followersTitle' => "Followers of ",
'friendsTitle' => "Friends of ",
'fromSource' => "from",
'hookTitle' => "Twitter",
'inReplyTo' => "in reply to %s",
'loadMore' => "Load more",
'loadMoreLoading' => "loading",
'myStatus' => "My Recent Status",
'noMoreTwitterCalls' => "You've used up all API calls for this hour. Please wait till the API counts are reset.",
'recreatedOAuthKeys' => "OAuth keys reset due to authenticy problems. Returning back to the board index",
'remainingApiCalls' => "Remaining API calls",
'replyTo' => "reply to ",
'searching' => "Searching...",
'searchResult' => "Search Result",
'shorten' => "shorten",
'shortenUrl' => "Shorten URL",
'singleStatusTitle' => "Viewing a single status from %s",
'tabMentions' => "Mentions",
'tabSearch' => "Search",
'tabTimeline' => "Timeline",
'tabUpdate' => "Update",
'tabUser' => "User",
'timeline' => "Timeline",
'ucpTwitter' => "Twitter Sidebar",
'ucpTwitterReset' => "Reset Twitter authentication",
'ucpTwitterResetDesc' => "Check the above box to reset OAuth authentication keys, or show the sidebar, if hided.",
'unFavorite' => "un-favorite this update",
'update' => "update",
'userTabDesc' => "Description:",
'userTabFollowers' => "Followers:",
'userTabFollowing' => "Following:",
'userTabLocation' => "Location:",
'userTabName' => "Name:",
'userTabTweets' => "Tweets",
'whatchaDoin' => "What are you doing?",
 ); 
