<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 14               */
/* CACHE FILE: Generated: Sun, 09 Dec 2012 17:06:47 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_ibEconomy_14 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['area_side_bar'] = array('area_is_active');
$this->_funcHooks['blockRowLotto'] = array('was_last_lotto_winner','eco_lottery_still_open');
$this->_funcHooks['blocks'] = array('sidebarclosed2','sidebarEnabled');
$this->_funcHooks['button_row'] = array('donationsOn');
$this->_funcHooks['cart_wrapper'] = array('show_one_click_buy','show_one_click_buy','show_one_click_buy');
$this->_funcHooks['editMemPtsPop'] = array('eco_worth_on');
$this->_funcHooks['init_js_css'] = array('useMinify','importrtlcss','importrtlcss','importrtlcss','importrtlcss');
$this->_funcHooks['memberInfoPane'] = array('hasShopItems');
$this->_funcHooks['memberProfileDonate'] = array('eco_donations_on','eco_can_edit_pts');
$this->_funcHooks['memPanePop'] = array('eco_worth_on','eco_worth_on','eco_welfare_on');
$this->_funcHooks['pointButton'] = array('eco_dons_on','eco_dons_on','eco_class_button');
$this->_funcHooks['profileTab'] = array('hasAssets','ptsPositive','ptsZero','ptsZero','ptsPositive','ptsZero','ptsZero','ecoWorthOn','hasShopItems','shopItemsOn','hasLogs','transactionsOn');
$this->_funcHooks['settings'] = array('eco_transactions_area','eco_portfolio_area','eco_bank_area','eco_stock_areas','eco_cc_areas','eco_lt_areas','eco_trading_area','eco_shopitem_area','eco_worth_on','eco_cash_area','eco_loans_area','eco_loans_area');
$this->_funcHooks['standings_row'] = array('addfriend','notus','sendpm','showassets','showTransactions','norep','posrep','negrep','norep','posrep','negrep','eco_worth_on','eco_worth_on');
$this->_funcHooks['standings_wrapper'] = array('filtermembers','filterwelfare','filterpoints','filterworth','eco_worth_on');
$this->_funcHooks['stats'] = array('eco_worth_on','showEcoTotals','eco_shopitems_area','activeNames','showEcoActive');
$this->_funcHooks['tab'] = array('active_tab');
$this->_funcHooks['transactions_wrapper'] = array('showMemberInput');
$this->_funcHooks['wrapper'] = array('sidebarclosed');


}

/* -- announce --*/
function announce($announcement) {
$IPBHTML = "";
$IPBHTML .= "" . (($this->settings['eco_general_ance_on'] && $this->settings['eco_general_ance']) ? ("
<div class='maintitle' style='text-align:center'><img src='{$this->settings['img_url']}/transmit_blue.png' />  {$this->settings['eco_general_name']} {$this->lang->words['global_announcement']}</div>
		<table class='ipb_table' id='eco_announcement' style='text-align:center'>
			<tr>
				<td class='row2'>{$announcement}</td>
			</tr>
		</table><br />
") : ("")) . "";
return $IPBHTML;
}

/* -- area_side_bar --*/
function area_side_bar($isActive, $areaLangName, $title, $moreURL) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['area_side_bar'] ) )
{
$count_14cb1bc568099cdbf134de6b17397bc5 = is_array($this->functionData['area_side_bar']) ? count($this->functionData['area_side_bar']) : 0;
$this->functionData['area_side_bar'][$count_14cb1bc568099cdbf134de6b17397bc5]['isActive'] = $isActive;
$this->functionData['area_side_bar'][$count_14cb1bc568099cdbf134de6b17397bc5]['areaLangName'] = $areaLangName;
$this->functionData['area_side_bar'][$count_14cb1bc568099cdbf134de6b17397bc5]['title'] = $title;
$this->functionData['area_side_bar'][$count_14cb1bc568099cdbf134de6b17397bc5]['moreURL'] = $moreURL;
}
$IPBHTML .= "<li " . (($isActive) ? ("class='active'") : ("")) . ">
						<a href='{$this->settings['base_url']}{$moreURL}' title='{$title}'>{$areaLangName}</a>
				</li>";
return $IPBHTML;
}

/* -- area_side_bars --*/
function area_side_bars($areas) {
$IPBHTML = "";
$IPBHTML .= "<div class='ipsVerticalTabbed_tabs ipsLayout_left'>
	<ul>
		{$areas}
	</ul>
</div>";
return $IPBHTML;
}

/* -- asset_row --*/
function asset_row($asset) {
$IPBHTML = "";
$IPBHTML .= "<tr id='{$asset['p_id']}'>
				<td>
					<img src='{$this->settings['img_url']}/eco_images/{$asset['image']}' title='{$asset['type']}' alt='type' />
				</td>
				<td>
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($asset) : '' ) . "
				</td>				
				<td>
					<span style='font-weight:bolder'>
						{$asset['title']} <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=invest&amp;area=single&amp;type={$asset['p_type']}&amp;id={$asset['p_type_id']}' class='__item __id{$asset['p_type_id']}__type_{$asset['p_type']}_{$asset['p_type_class']}' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a>
					</span>
				</td>			
				<td>
					<span style='font-size:0.85em'>{$asset['type']}</span>
				</td>
				<td>
					<span style='font-size:0.85em'>{$asset['quantity']}</span>
				</td>
				<td>
					<span style='font-size:0.85em'>{$asset['purchase_date']}</span>
				</td>
			</tr>";
return $IPBHTML;
}

/* -- asset_wrapper --*/
function asset_wrapper($content, $otherSW, $memName, $pages, $assetsDD) {
$IPBHTML = "";
$IPBHTML .= "<div class='maintitle ipsFilterbar'>
				<ul class='ipsList_inline ipsType_smaller'>
					<li " . (($this->request['sort'] == 'members_display_name') ? (" class='active'") : ("")) . "><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=portfolio&amp;member_id={$this->request['member_id']}&amp;mname={$memName}&amp;p_type={$this->request['p_type']}&amp;sort=members_display_name&amp;sw={$otherSW}'>{$this->lang->words['member']}</a></li>
					<li " . (($this->request['sort'] == 'p_type_id') ? (" class='active'") : ("")) . "><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=portfolio&amp;member_id={$this->request['member_id']}&amp;mname={$memName}&amp;p_type={$this->request['p_type']}&amp;sort=p_type_id&amp;sw={$otherSW}'>{$this->lang->words['name']}</a></li>
					<li " . (($this->request['sort'] == 'p_type') ? (" class='active'") : ("")) . "><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=portfolio&amp;member_id={$this->request['member_id']}&amp;mname={$memName}&amp;p_type={$this->request['p_type']}&amp;sort=p_type&amp;sw={$otherSW}'>{$this->lang->words['type']}</a></li>
					<li " . (($this->request['sort'] == 'p_amount') ? (" class='active'") : ("")) . "><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=portfolio&amp;member_id={$this->request['member_id']}&amp;mname={$memName}&amp;p_type={$this->request['p_type']}&amp;sort=p_amount&amp;sw={$otherSW}'>{$this->lang->words['Quantity']}</a></li>
					<li " . (($this->request['sort'] == 'p_purch_date') ? (" class='active'") : ("")) . "><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=portfolio&amp;member_id={$this->request['member_id']}&amp;mname={$memName}&amp;p_type={$this->request['p_type']}&amp;sort=p_purch_date&amp;sw={$otherSW}'>{$this->lang->words['aquired']}</a></li>
					<li " . (($memName || $this->request['p_type']) ? (" class='active'") : ("")) . "><a href='#custom_menucontent' id='custom'>Custom</a></li>
				</ul>
			</div>
			<div id='custom_menucontent' class='ipbmenu_content ipsPad'>
				<form action='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=portfolio' method='post'>
				<strong>{$this->lang->words['member']}</strong><br />
				<input type=\"text\" class='input_text' id='mem_name1' name=\"mem_name\" value=\"{$memName}\" />
				<br /><br />
				<strong>{$this->lang->words['type']}</strong><br />
				{$assetsDD}
				<br /><br />
				<input type=\"submit\" value=\"Submit\" class=\"input_submit\" />
				</form>
			</div>
			<script type='text/javascript'>
				new ipb.Menu( $('custom'), $('custom_menucontent'), { stopClose: true } );
			</script>
			<table class='ipb_table'>
			<tr class='header'>
				<th scope='col' width='5%'>&nbsp;</th>
				<th scope='col' width='15%'>{$this->lang->words['member']}</th>
				<th scope='col' width='25%'>{$this->lang->words['name']}</th>
				<th scope='col' width='15%'>{$this->lang->words['type']}</th>
				<th scope='col' width='15%'>{$this->lang->words['Quantity']}</th>
				<th scope='col' width='20%'>{$this->lang->words['aquired']}</th>
			</tr>
            {$content}
		</table>
		<div style='margin:10px;'>
			{$pages}
		</div>
<!--		
<script type=\"text/javascript\">
	document.observe(\"dom:loaded\", function(){
		var url = ipb.vars['base_url'] + 'app=core&module=ajax&section=findnames&do=get-member-names&secure_key=' + ipb.vars['secure_hash'] + '&name=';
		new ipb.Autocomplete( $('mem_name1'), { multibox: false, url: url, templates: { wrap: ipb.templates['autocomplete_wrap'], item: ipb.templates['autocomplete_item'] } } );
	});
</script>	
-->";
return $IPBHTML;
}

/* -- block --*/
function block($content='',$block='') {
$IPBHTML = "";
$IPBHTML .= "" . (($block['sb_boxed']) ? ("<div class='ipsSideBlock clearfix' style='background-color:{$block['sb_bg_color']};color:{$block['sb_font_color']}'>
	<h3>" . (($block['sb_pic']) ? ("<img src='{$this->settings['img_url']}/eco_images/{$block['sb_pic']}' alt='{$this->lang->words['icon']}' />") : ("")) . " {$block['sb_title']}</h3>
		<div class='_sbcollapsable'>
			<ul class='ipsList_withminiphoto'>
				{$content}
			</ul>
		</div>
	</div>") : ("
	<div style='margin-bottom:10px;padding:10px;background-color:{$block['sb_bg_color']};color:{$block['sb_font_color']}'>
		<div class='_sbcollapsable'>	
			<ul class='ipsList_withminiphoto'>
				{$content}
			</ul>
		</div>
	</div>	
")) . "";
return $IPBHTML;
}

/* -- blockMem --*/
function blockMem($content='',$block='') {
$IPBHTML = "";
$IPBHTML .= "" . (($block['sb_boxed']) ? ("<div class='ipsSideBlock clearfix'>
		<h3>" . (($block['sb_pic']) ? ("<img src='{$this->settings['img_url']}/eco_images/{$block['sb_pic']}' alt='{$this->lang->words['icon']}' />") : ("")) . " {$block['sb_title']}</h3>
		<div class='_sbcollapsable'>
			<ul class='ipsList_withminiphoto'>
			{$content}
			</ul>
		</div>
	</div>") : ("
	<div style='margin-bottom:10px;padding:10px;background-color:{$block['sb_bg_color']};color:{$block['sb_font_color']};'>
		<ul class='ipsList_withminiphoto'>
		{$content}
		</ul>
	</div>
")) . "";
return $IPBHTML;
}

/* -- blockRow --*/
function blockRow($row='',$block='') {
$IPBHTML = "";
$IPBHTML .= "<li class='clearfix' style='background-color:{$block['sb_bg_color']}'><a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab={$row['tab']}&amp;area=single&amp;type={$row['type']}&amp;id={$row['id']}&amp;bank_type={$row['s_type']}\">{$row['title']}</a> <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab={$row['tab']}&amp;area=single&amp;type={$row['type']}&amp;id={$row['id']}&amp;bank_type={$row['s_type']}' class='__item __id{$row['id']}__type_{$row['type']}_{$row['s_type']}' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a>
		<span style='font-size:0.85em'>" . (($block['sb_show_text']) ? ("<br />{$block['text']}") : ("")) . ": {$row['figure']} </span><br />
		<span class='date'><abbr class=\"published\" title=\"{$this->lang->words['added_on']}\">{$this->lang->words['added_on']}: {$row['start_date']}</abbr></span></li>";
return $IPBHTML;
}

/* -- blockRowLotto --*/
function blockRowLotto($row='',$block='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['blockRowLotto'] ) )
{
$count_0bbf8c1cfac0658f856cd43877fd320b = is_array($this->functionData['blockRowLotto']) ? count($this->functionData['blockRowLotto']) : 0;
$this->functionData['blockRowLotto'][$count_0bbf8c1cfac0658f856cd43877fd320b]['row'] = $row;
$this->functionData['blockRowLotto'][$count_0bbf8c1cfac0658f856cd43877fd320b]['block'] = $block;
}
$IPBHTML .= "<li class='clearfix' style='background-color:{$block['sb_bg_color']}'>
		" . (($row['prevWinnerMemData']['member_id'] > 0) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$row['prevWinnerMemData']['member_id']}", "public",'' ), "{$row['prevWinnerMemData']['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink left'><img src='{$row['prevWinnerMemData']['pp_mini_photo']}' alt=\"{$row['prevWinnerMemData']['members_display_name']}{$this->lang->words['users_photo']}\" class='ipsUserPhoto ipsUserPhoto_mini' /></a>
			<div class='list_content'>
				" . (($row['prevWinnerMemData']['members_display_name']) ? ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($row['prevWinnerMemData']) : '' ) . "") : ("{$this->settings['guest_name_pre']}{$row['prevWinnerMemData']['starter_name']}{$this->settings['guest_name_suf']}")) . " &middot; {$this->settings['eco_general_cursymb']}{$row['prevWinnings']}<br />
				<p class='desc ipsType_smaller'>
					{$this->lang->words['last_winner']}
				</p>
			</div>") : ("")) . "
	</li>
	<li class='clearfix' style='background-color:{$block['sb_bg_color']}'>
		<div class='info'>
			<dt>{$this->lang->words['draw']}</dt>
			<dd><a href=\"{$this->settings['base_url']}app=ibEconomy&amp;tab=cash&amp;area=single&amp;type=lotto&amp;id={$row['id']}&amp;type=lottery&amp;id={$row['l_id']}\">{$row['l_draw_date_no_time']}</a> <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=cash&amp;area=single&amp;type=lotto&amp;id={$row['id']}&amp;bank_type={$row['s_type']}' class='__item __id{$row['l_id']}__type_lottery_Item' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a></dd>
			<dt>{$this->lang->words['pot_size']}</dt>
			<dd>{$this->settings['eco_general_cursymb']}{$row['l_final_pot_size']}</dd>                   
			<dt>{$this->lang->words['price']}</dt>			
			<dd>{$this->settings['eco_general_cursymb']}{$row['cost']}</dd>
			<dt>{$this->lang->words['yours']}</dt>
			<dd>{$row['your_num_total_tix_formatted']}</dd>
			<dt>{$this->lang->words['sold']}</dt>
			<dd>{$row['l_tix_purchased']}</dd>
			" . (($row['tix_still_4_sale']) ? ("
				<form action='{$this->settings['base_url']}app=ibEconomy&do=add_to_cart' method='post'>
				<input type='hidden' name='item_id' value='lottery_{$row['l_id']}' />
				<dt><input type='text' name='quantity' size='2' /></dt>			
					<dd><input type='submit' class='input_submit' name='submit' value='{$this->lang->words['add_to_cart']}' /></dd>
				</form>
			") : ("")) . "
		</div>
	</li>";
return $IPBHTML;
}

/* -- blockRowMem --*/
function blockRowMem($r='',$block='') {
$IPBHTML = "";
$IPBHTML .= "<li class='clearfix'>
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", "public",'' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink left'><img src='{$r['pp_mini_photo']}' alt=\"{$r['members_display_name']}{$this->lang->words['users_photo']}\" class='ipsUserPhoto ipsUserPhoto_mini' /></a>
			<div class='list_content'>
				" . (($block['sb_show_text']) ? (" {$block['text']}: ") : ("")) . "{$r['figure']}<br />
				<p class='desc ipsType_smaller'>
					" . (($r['members_display_name']) ? ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($r) : '' ) . "") : ("{$this->settings['guest_name_pre']}{$r['starter_name']}{$this->settings['guest_name_suf']}")) . "
				</p>
			</div>
		</li>";
return $IPBHTML;
}

/* -- blocks --*/
function blocks($blocks) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['blocks'] ) )
{
$count_f097f65de24fea2425197f2185f9f229 = is_array($this->functionData['blocks']) ? count($this->functionData['blocks']) : 0;
$this->functionData['blocks'][$count_f097f65de24fea2425197f2185f9f229]['blocks'] = $blocks;
}
$IPBHTML .= "<div id='index_stats' class='ipsLayout_right clearfix' " . ((IPSCookie::get('hide_sidebar') == '1') ? ("style='display: none'") : ("")) . ">
	{$blocks}
</div>
" . (($this->settings['eco_display_sidebar_on'] && !in_array($this->registry->output->skin['set_id'], explode(',', $this->settings['eco_display_sb_skins']))) ? ("
	<a href='#' id='toggle_sidebar' title='' data-closed=\"&laquo;\" data-open=\"&times;\">&nbsp;</a>
") : ("")) . "";
return $IPBHTML;
}

/* -- button_row --*/
function button_row($my_points, $leftButtons) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['button_row'] ) )
{
$count_f119ebb7f5ba5c30039c04f319e90f31 = is_array($this->functionData['button_row']) ? count($this->functionData['button_row']) : 0;
$this->functionData['button_row'][$count_f119ebb7f5ba5c30039c04f319e90f31]['my_points'] = $my_points;
$this->functionData['button_row'][$count_f119ebb7f5ba5c30039c04f319e90f31]['leftButtons'] = $leftButtons;
}
$IPBHTML .= "<div class='topic_controls'> 
	<ul class='topic_buttons'>
		" . (($this->settings['eco_cashier_on']) ? ("
			<li><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=buy&amp;area=cart' title='{$this->lang->words['view_cart']}'><img src='{$this->settings['img_url']}/eco_images/cart.png' alt='Icon' /> {$this->lang->words['shopping_cart']}</a></li>
		") : ("")) . "
			<li class='non_button'><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=me' title='{$this->lang->words['my_portfolio']}'><img src='{$this->settings['img_url']}/eco_images/money.png' alt='Icon' /> {$this->lang->words['my_points']}: {$my_points}</a></li>

	</ul>
	" . (($this->settings['eco_dons_on'] && in_array('don', explode(',',$this->settings['eco_left_buttons']))) ? ("<li class='ipsButton_secondary'><a class='ibEconomy_popup' id='do_donate' href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=find_member' title='{$this->lang->words['quick_donate']}'><img src='{$this->settings['img_url']}/eco_images/group_go.png' alt='Icon' /> {$this->lang->words['quick_donate']}</a></li>") : ("")) . "
{$leftButtons}
	</div><br />";
return $IPBHTML;
}

/* -- cart_row --*/
function cart_row($item) {
$IPBHTML = "";
$IPBHTML .= "<tr id='{$item['c_id']}'>
				<td>
					{$item['image_thumb_link']}
				</td>
				<td>
					<span style='font-weight:bolder'>
						{$item['title_line']}
					</span>
				</td>
				<td>
					{$item['desc_line']}
				</td>				
				<td class=' short'>
					" . ((intval($item['cost']) > 0) ? ("{$this->settings['eco_general_cursymb']}") : ("")) . "{$item['cost']}
				</td>
				<td class='short'>
					<table class='ipb_table'>
						<tr>
							<td style='text-align:right'>
								<span class='desc'>{$item['pre_amount_text']} </span>
							</td>
							<td style='text-align:right'>
								<input type='hidden' name='item_id_{$item['c_id']}' value='{$item['c_type_id']}' />
								<input type='hidden' name='bank_type_{$item['c_id']}' value='{$item['c_type_class']}' />
								<input type='hidden' name='item_type_{$item['c_id']}' value='{$item['l_type']}' />
								<input type='hidden' name='old_amount_{$item['c_id']}' value='{$item['amount']}' />
								<input type='text' size='5' name='new_amount_{$item['c_id']}' value='{$item['amount']}' />
							</td>
						</tr>
					</table>
				</td>
				<td class=' short'>
					{$this->settings['eco_general_cursymb']}{$item['total']}
				</td>
				<td class=' short'>
					<input type='checkbox' class='input_check item_check' name='update_me[]' id='item_{$item['c_id']}' value='{$item['c_id']}' />
				</td>
			</tr>";
return $IPBHTML;
}

/* -- cart_wrapper --*/
function cart_wrapper($content='', $totals='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['cart_wrapper'] ) )
{
$count_f3a21f6039bd0785e33dba382a8e1e5e = is_array($this->functionData['cart_wrapper']) ? count($this->functionData['cart_wrapper']) : 0;
$this->functionData['cart_wrapper'][$count_f3a21f6039bd0785e33dba382a8e1e5e]['content'] = $content;
$this->functionData['cart_wrapper'][$count_f3a21f6039bd0785e33dba382a8e1e5e]['totals'] = $totals;
}
$IPBHTML .= "<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=update_cart' method='post' onsubmit=\"return confirm('{$this->lang->words['confirm_cart_update']}');\">
		<div class='maintitle'>{$this->lang->words['items']}</div>
		<table class='ipb_table' id='message_table'>
			<tr class='header'>
				<th scope='col'>&nbsp;</th>
				<th scope='col'>{$this->lang->words['name']}</th>
				<th scope='col'>{$this->lang->words['type']}</th>
				<th scope='col' class=' short'>{$this->lang->words['cost']}</th>
				<th scope='col' class=' short'>{$this->lang->words['amount']}</th>
				<th scope='col' class=' short'>{$this->lang->words['total']}</th>
				<th scope='col' class=' short'><input type='checkbox' class='input_check' id='item_checkall' value='1' /></th>
			</tr>
            {$content}
		</table>
		<div class='moderation_bar rounded with_action'>
			<select name='method' class='input_select'>
				<optgroup label='{$this->lang->words['with_selected']}...'>
					<option value='delete'>{$this->lang->words['delete']}</option>
					<option value='update_quantity'>{$this->lang->words['update_quantity']}</option>
			</select>
			<input type='submit' class='input_submit' value='{$this->lang->words['go']}' />
		</div>
	</form>
	<table class='ipb_table' id='message_table'>
		<tr style='text-align:right;'>
			<td style='width:75%'>
				{$this->lang->words['subtotal']}
			</td>
			<td>
				{$this->settings['eco_general_cursymb']}{$totals['sub']}
			</td>
		</tr>				
		<tr style='text-align:right;'>				
			<td style='width:75%'>
				{$this->lang->words['fees_and_taxes']}
			</td>
			<td>
				{$this->settings['eco_general_cursymb']}{$totals['fees']}
			</td>
		</tr>
		<tr style='text-align:right;'>				
			<td style='width:75%'>
				<strong>{$this->lang->words['grand_total']}</strong>
			</td>
			<td>
				<strong>{$totals['grand']} {$this->settings['eco_general_currency']}</strong>
			</td>				
		</tr>
	</table>
	<fieldset class='submit'>
		<form method='post' action='{$this->settings['base_url']}app=ibEconomy&amp;tab=buy&amp;area=checkout'>
			" . (($this->settings['eco_general_one_click_buy'] != 'only') ? ("
				<input type='submit' name=\"submit\" class='input_submit alt' value='{$this->lang->words['checkout']}' />
			") : ("")) . "
			" . (($this->settings['eco_general_one_click_buy'] == 'on') ? ("
				&nbsp;&nbsp;{$this->lang->words['or']}&nbsp;&nbsp;
			") : ("")) . "
			" . ((in_array($this->settings['eco_general_one_click_buy'], array('only', 'on'))) ? ("
				<a href='{$this->settings['base_url']}app=ibEconomy&amp;do=purchase&amp;one_click_buy=true' name=\"one_click_buy\" class='input_submit' id='one_click_buy'  value='one_click_buy'>{$this->lang->words['one_click_buy']}</a>
			") : ("")) . "
		</form>
	</fieldset>";
return $IPBHTML;
}

/* -- checkOut_row --*/
function checkOut_row($payment_dd) {
$IPBHTML = "";
$IPBHTML .= "<script type='text/javascript' src='{$this->settings['js_app_url']}ips.payment.js'></script>
<div id='question_#1_wrap' style='display: show; text-align:right'>
							<span >
								{$payment_dd}
								<input type='text' name='payment_amt' size='10' />
							</span>
</div>
<fieldset id='payment_fieldset' style='display: none'>
<script type='text/javascript'>
//<![CDATA[
	ipb.payment.maxQuestions = parseInt( 1 );
	ipb.payment.maxChoices = parseInt( 5 );
	ipb.payment.isPublicpayment = parseInt( 5 );
	ipb.payment.showOnLoad = 0;
	
	ipb.templates['payment_question'] = 	new Template(\"<li class='field question' id='question_#{qid}_wrap' style='display: none'>\" +
											\"	<div>\" + 
											\"		<ol style='text-align:right' id='choices_for_#{qid}'></ol>\" + 
											\"		<br /><ul style='text-align:right;padding-top:2px;padding-bottom:15px;'>\" +
											\"			<li><a href='#' style='text-decoration: none;outline: none;' id='add_choice_#{qid}' title='{$this->lang->words['add_payment_option']}'>" . $this->registry->getClass('output')->getReplacement("add_poll_choice") . " {$this->lang->words['add_payment_option']}</a></li>\" +
											\"		</ul>\" +
											\"	</div>\" +
											\"</li>\");
	ipb.templates['payment_choice'] = 		new Template(\"<li id='payment_#{qid}_#{cid}_wrap' style='display: none;padding-bottom:5px'><input type='hidden' value='#{cid}' name='payment_ids[]' /> {$payment_dd}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type='text' id='payment_#{qid}_#{cid}_votes' name='amount_#{cid}' value='#{votes}' class='input_text' size='5' /> <a href='#' id='remove_#{qid}_#{cid}' title='{$this->lang->words['remove_payment']}'>" . $this->registry->getClass('output')->getReplacement("remove_poll_choice") . "</a></li>\");
//]]>
</script>
<div id='payment_form'>
	<div id='add_payment' style='display: none'>
		<ul class='topic_buttons'>
			<li><a href='#'><img src='{$this->settings['img_url']}/eco_images/money_add.png'> {$this->lang->words['open_payment_options']}</a></li>
		</ul>
	</div>
	<fieldset id='payment_wrap' style='display: none' class='clear'>
		<ul id='payment_container'>
		</ul>
		<div>
			<ul class='topic_buttons'>
				<li id='close_payment'><a href='#'>" . $this->registry->getClass('output')->getReplacement("close_poll_form") . " {$this->lang->words['close_payment_options']}</a></li>
			</ul>
		</div>
	</fieldset>
</div>
</fieldset>
<script type='text/javascript'>
	$('payment_fieldset').show();
	document.getElementById(\"question_#1_wrap\").style.display = 'none';	
</script>";
return $IPBHTML;
}

/* -- checkOut_wrapper --*/
function checkOut_wrapper($content='', $totals='') {
$IPBHTML = "";
$IPBHTML .= "<div class='maintitle'>{$this->lang->words['payment_options']}</div>
		<table class='ipb_table' id='message_table'>
			<tr class='header'>
				<th style='width:45%'>&nbsp;</th>
				<th style='width:35%;padding-right:45px;text-align:right'>{$this->lang->words['payment_type']}</th>				
				<th style='width:20%;padding-right:20px;text-align:right'>{$this->lang->words['charge_amount']}</th>
			</tr>
			<tr>
				<td>
					<span style='font-weight:bolder'>
						{$this->lang->words['total_due']}: {$totals['grand']} {$this->settings['eco_general_currency']}
					</span>
				</td>
				<td colspan='2'>
					<table>
						<tr>
							<td>
								<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=purchase' method='post' onsubmit=\"return confirm('{$this->lang->words['purchase_conf']}');\">
								{$content}
							</td>
						</tr>					
					</table>
				</td>
			</tr>
		</table>
		<fieldset class='submit'>
				<input type='submit' class='input_submit' value='{$this->lang->words['purchase']}' />
		</form>
	</fieldset>";
return $IPBHTML;
}

/* -- donatePop --*/
function donatePop() {
$IPBHTML = "";
$IPBHTML .= "<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=donate' method='post'>
		<table class='ipb_table'>
			<tr class='header'>
				<th colspan='2' style='text-align:center'><img src='{$this->settings['img_url']}/eco_images/group_go.png' alt='Icon' /> {$this->lang->words['making_donation']}</th>
			</tr>
			<tr class='row1'>
				<td style='text-align:right'>
					{$this->lang->words['don_recip']}:
				</td>
				<td style='text-align:left'>
					<input type=\"text\" class='input_text' id='mem_name1' name=\"mem_name\" size=\"30\" value=\"{$mem_name}\" tabindex=\"0\" />
				</td>				
			</tr>
			<tr class='row2'>
				<td style='text-align:right'>
					{$this->lang->words['reason']}:
				</td>
				<td style='text-align:left'>
					<input type='text' size='50%' maxlength='100' name='donation_reason' />
				</td>				
			</tr>
			<tr class='row1'>
				<td style='text-align:right'>
					{$this->lang->words['amount']}:
				</td>
				<td style='text-align:left'>
					<input type='text' size='5' maxlength='20' name='donation_amount' />
				</td>				
			</tr>			
		</table>
		<fieldset class='submit'>
				<input type='submit' class='input_submit' value='{$this->lang->words['donate']}' />
		</form>		
		</fieldset>";
return $IPBHTML;
}

/* -- editMemPtsPop --*/
function editMemPtsPop($member, $url) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['editMemPtsPop'] ) )
{
$count_9a1f8b17eab85393656d464e5c3168f1 = is_array($this->functionData['editMemPtsPop']) ? count($this->functionData['editMemPtsPop']) : 0;
$this->functionData['editMemPtsPop'][$count_9a1f8b17eab85393656d464e5c3168f1]['member'] = $member;
$this->functionData['editMemPtsPop'][$count_9a1f8b17eab85393656d464e5c3168f1]['url'] = $url;
}
$IPBHTML .= "<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=edit_member_pts' method='post'>
	<table class='ipb_table'>
		<tr class='header'>
			<th colspan='2' style='text-align:center'><img src='{$this->settings['img_url']}/eco_images/wrench_orange.png' alt='Icon' /> {$this->lang->words['editing']} {$this->settings['eco_general_currency']}</th>
		</tr>
		<tr>
			<td style='text-align:center'>
			<input type='hidden' name='id' value='{$member['member_id']}' />
			<input type='hidden' name='to_name' value='{$member['members_display_name']}' />
			<input type='hidden' name='from_url' value='{$url}' />
			<input type='hidden' name='old_point_total' value='{$member['eco_points']}' />
				<a style='font-weight:bolder' href=\"{$this->settings['base_url']}app=ibEconomy&tab=global&area=member&id={$member['member_id']}\" title='{$this->lang->words['view_eco_profile']}'>{$member['formatted_name']}</a><br /><br />
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'><img src='{$member['pp_main_photo']}' width='{$member['pp_main_width']}' height='{$member['pp_main_height']}' alt=\"{$member['members_display_name']}{$this->lang->words['users_photo']}\" class='photo' /></a>
			</td>
			<td style='text-align:left'>
			" . (($this->settings['eco_worth_on'] && $this->settings['eco_rankings_on']) ? ("
			<p class='message user_status'><img src='{$this->settings['img_url']}/eco_images/money.png' alt='{$this->lang->words['total_worth']}' title='{$this->lang->words['total_worth']}' />&nbsp;<strong>{$this->lang->words['total_worth']} {$this->lang->words['rank']}: <span style='font-size:1.25em'>#" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_worth_rank'] ) . "</span></strong></p>
			") : ("")) . "
			<table class='ipb_table'>
				<tr>
					<td style='font-weight:bold'>{$this->lang->words['total']} {$this->settings['eco_general_currency']}</td>
					<td><input type='text' size='8' maxlength='20' name='new_point_total' value='{$member['eco_points']}' /></td>
				</tr>
				<br />
			</table>
			</td>				
		</tr>
		<tr>
			<td style='text-align:right'>
				{$this->lang->words['or_add_amount']}:
			</td>
			<td style='text-align:left'>
				<input type='text' size='5' maxlength='20' name='edit_amount' />
			</td>				
		</tr>		
		<tr>
			<td style='text-align:right'>
				{$this->lang->words['reason']}:
			</td>
			<td style='text-align:left'>
				<input type='text' size='50%' maxlength='100' name='edit_reason' />
			</td>				
		</tr>			
	</table>
	<fieldset class='submit'>
			<input type='submit' class='input_submit' value='{$this->lang->words['edit']} {$this->settings['eco_general_currency']}' />
	</form>		
	</fieldset>";
return $IPBHTML;
}

/* -- error --*/
function error($text='') {
$IPBHTML = "";
$IPBHTML .= "<div class='message error' style='margin:15px'>{$text}</div>";
return $IPBHTML;
}

/* -- find_member --*/
function find_member($content='', $totals='') {
$IPBHTML = "";
$IPBHTML .= "<div class='ipsBox'>
	<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=do_find_member' method='post'>
	<div class='ipsBox_container ipsPad'>
		<ul class='ipsForm ipsForm_vertical'>
		<li class='ipsField'>
			<label class='ipsField_title'>{$this->lang->words['input_member_name']} <spanclass='ipsForm_required'>*</span></label>
			<div class='ipsField_content'>
				<input type=\"text\" class='input_text' id='mem_name1' name=\"mem_name\" size=\"30\" value=\"{$mem_name}\" tabindex=\"0\" /><br />
			</div>
		</li>
		</ul>
	</div>
	<fieldset class='submit'>
		<input type='submit' class='input_submit' value='{$this->lang->words['find_member']}' />
	</fieldset>
	</form>
</div>

<script type=\"text/javascript\">
	document.observe(\"dom:loaded\", function(){
		var url = ipb.vars['base_url'] + 'app=core&module=ajax&section=findnames&do=get-member-names&secure_key=' + ipb.vars['secure_hash'] + '&name=';
		new ipb.Autocomplete( $('mem_name1'), { multibox: false, url: url, templates: { wrap: ipb.templates['autocomplete_wrap'], item: ipb.templates['autocomplete_item'] } } );
	});
</script>";
return $IPBHTML;
}

/* -- footer --*/
function footer() {
$IPBHTML = "";
$IPBHTML .= "<br class='clear' />
<div id='board_footer' style='min-height:15px;'>
<p id='copyright' class='right'>
	ibEconomy {$this->caches['app_cache']['ibEconomy']['app_version']} &copy; 2011 &nbsp;<a href='http://emoneycodes.com/forums/' title='emoneyCodes.com - (e$) Mods'>emoney - (e$) Mods</a>.
</p>
</div>";
return $IPBHTML;
}

/* -- init_js_css --*/
function init_js_css() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['init_js_css'] ) )
{
$count_a9eba06bda90b97dd058d02b4deea494 = is_array($this->functionData['init_js_css']) ? count($this->functionData['init_js_css']) : 0;
}
$IPBHTML .= "<!--JS-->
<script type='text/javascript' src='{$this->settings['js_app_url']}ips.ibEconomy.js'></script>
<!--CSS-->
" . (($this->settings['use_minify']) ? ("
	<link rel=\"stylesheet\" type=\"text/css\" media='screen' href=\"{$this->settings['board_url']}/public/min/index.php?f=public/style_css/{$this->registry->output->skin['_csscacheid']}/ipb_ucp.css,public/style_css/{$this->registry->output->skin['_csscacheid']}/ipb_mlist.css\" />
") : ("
	<link rel=\"stylesheet\" type=\"text/css\" media='screen' href=\"{$this->settings['board_url']}/public/style_css/{$this->registry->output->skin['_csscacheid']}/ipb_ucp.css\" />
	<link rel=\"stylesheet\" type=\"text/css\" media='screen' href=\"{$this->settings['board_url']}/public/style_css/{$this->registry->output->skin['_csscacheid']}/ipb_mlist.css\" />
")) . "

<!--RTL FIX-->
<script type='text/javascript'>
	var isRTL	= false;
	var rtlIe	= '';
	var rtlFull	= '';
</script>

" . (($this->lang->words['_isRtl'] AND file_exists( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/' . $this->registry->output->skin['_csscacheid'] . '/ipb_rtl.css' )) ? ("
	<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl.css\" />
	<script type='text/javascript'>
		var rtlFull	= \"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl.css\";
		var isRTL	= true;
	</script>
") : ("" . (($this->lang->words['_isRtl'] AND file_exists( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/ipb_rtl.css' )) ? ("
		<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/ipb_rtl.css\" />
		<script type='text/javascript'>
			var rtlFull	= \"{$this->settings['public_dir']}style_css/ipb_rtl.css\";
			var isRTL	= true;
		</script>
	") : ("")) . "")) . "
" . (($this->lang->words['_isRtl'] AND file_exists( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/' . $this->registry->output->skin['_csscacheid'] . '/ipb_rtl_ie.css' )) ? ("
	<!--[if lte IE 7]>
	<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl_ie.css\" />
	<![endif]-->
	<script type='text/javascript'>
		var rtlIe	= \"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl_ie.css\";
	</script>
") : ("" . (($this->lang->words['_isRtl'] AND file_exists( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/ipb_rtl_ie.css' )) ? ("
		<!--[if lte IE 7]>
		<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/ipb_rtl_ie.css\" />
		<![endif]-->
		<script type='text/javascript'>
			var rtlIe	= \"{$this->settings['public_dir']}style_css/ipb_rtl_ie.css\";
		</script>
	") : ("")) . "")) . "";
return $IPBHTML;
}

/* -- leftButton --*/
function leftButton($button) {
$IPBHTML = "";
$IPBHTML .= "<li class='ipsButton_secondary' style='margin-left:3px;'><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab={$button['tab']}&amp;area={$button['area']}' title='{$button['text']}'><img src='{$this->settings['img_url']}/eco_images/{$button['image']}' alt='Icon' /> {$button['text']}</a> </li>";
return $IPBHTML;
}

/* -- member --*/
function member($memberRow, $member) {
$IPBHTML = "";
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("memberlist", "0" ) . "		
	<table class='ipb_table'>
		<div class='ipsBox_container ipsPad' id='mlist_content'>
			<ul class='ipsMemberList'>
				{$memberRow}
			</ul>		
		</div>		
	</table>
	<div style=padding:10px;'>
		{$member['eco_stats']}
	</div>";
return $IPBHTML;
}

/* -- memberInfoPane --*/
function memberInfoPane($member, $miniShopItemBox) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['memberInfoPane'] ) )
{
$count_096990f7e6135feb847d071785e48092 = is_array($this->functionData['memberInfoPane']) ? count($this->functionData['memberInfoPane']) : 0;
$this->functionData['memberInfoPane'][$count_096990f7e6135feb847d071785e48092]['member'] = $member;
$this->functionData['memberInfoPane'][$count_096990f7e6135feb847d071785e48092]['miniShopItemBox'] = $miniShopItemBox;
}
$IPBHTML .= "" . (($miniShopItemBox) ? ("
		<br />{$miniShopItemBox}
	") : ("")) . "";
return $IPBHTML;
}

/* -- memberProfileDonate --*/
function memberProfileDonate($memberID) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['memberProfileDonate'] ) )
{
$count_eff7ed3f5c70f01d0b62ba6b872b8701 = is_array($this->functionData['memberProfileDonate']) ? count($this->functionData['memberProfileDonate']) : 0;
$this->functionData['memberProfileDonate'][$count_eff7ed3f5c70f01d0b62ba6b872b8701]['memberID'] = $memberID;
}
$IPBHTML .= "" . (($this->settings['eco_dons_on']) ? ("
	<li class='ibEconomy_MemPanePop ipsButton_secondary' id='do_member_{$memberID}_{$this->request['app']}_{$this->request['showuser']}_{$this->request['module']}'><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=member&amp;id={$memberID}' title='{$this->lang->words['view_my']} {$this->settings['eco_general_name']} {$this->lang->words['stats_and_donate_me_some']} {$this->settings['eco_general_currency']}!'><img src='{$this->settings['img_url']}/eco_images/money_add.png' /> {$this->lang->words['donate']} {$this->settings['eco_general_currency']}</a>
	</li>
") : ("")) . "
" . (($this->memberData['g_eco_edit_pts']) ? ("
	<li class='ibEconomy_MemPanePop ipsButton_secondary' id='do_edit_{$memberID}_{$this->request['app']}_{$this->request['showuser']}_{$this->request['module']}'><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=member&amp;id={$memberID}' title='{$this->lang->words['edit_my']} {$this->settings['eco_general_currency']}'><img src='{$this->settings['img_url']}/eco_images/wrench_orange.png' /> {$this->lang->words['edit']} {$this->settings['eco_general_currency']}</a>
	</li>
") : ("")) . "";
return $IPBHTML;
}

/* -- memberProfilePts --*/
function memberProfilePts($member) {
$IPBHTML = "";
$IPBHTML .= "<li> 
	<span class='row_title'>{$this->settings['eco_general_currency']}:</span> 
	<span class='row_data'>" . $this->registry->getClass('class_localization')->formatNumber( $member['pts'],$this->registry->ecoclass->decimal ) . "" . (($member['rank'] > 0 && $this->settings['eco_rankings_on']) ? (" <span title='{$this->lang->words['my_ranking']}'>(#" . $this->registry->getClass('class_localization')->formatNumber( $member['rank'] ) . ")</span>") : ("")) . "</span> 
</li>";
return $IPBHTML;
}

/* -- memPanePop --*/
function memPanePop($member, $url) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['memPanePop'] ) )
{
$count_72d5b97df13b23388f0a634598d2b184 = is_array($this->functionData['memPanePop']) ? count($this->functionData['memPanePop']) : 0;
$this->functionData['memPanePop'][$count_72d5b97df13b23388f0a634598d2b184]['member'] = $member;
$this->functionData['memPanePop'][$count_72d5b97df13b23388f0a634598d2b184]['url'] = $url;
}
$IPBHTML .= "<form action='{$this->settings['base_url']}app=ibEconomy&amp;do=donate' method='post'>
		<table class='ipb_table'>
			<tr class='header'>
				<th colspan='2' style='text-align:center'><img src='{$this->settings['img_url']}/eco_images/group_go.png' alt='Icon' /> {$this->lang->words['making_donation']}</th>
			</tr>
			<tr>
				<td style='text-align:center'>
				<input type='hidden' name='id' value='{$member['member_id']}' />
				<input type='hidden' name='to_name' value='{$member['members_display_name']}' />
				<input type='hidden' name='from_url' value='{$url}' />
					<a style='font-weight:bolder' href=\"{$this->settings['base_url']}app=ibEconomy&tab=global&area=member&id={$member['member_id']}\" title='{$this->lang->words['view_eco_profile']}'>{$member['formatted_name']}</a><br /><br />
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'><img src='{$member['pp_main_photo']}' width='{$member['pp_main_width']}' height='{$member['pp_main_height']}' alt=\"{$member['members_display_name']}{$this->lang->words['users_photo']}\" class='photo' /></a>
				</td>
				<td style='text-align:left'>
				" . (($this->settings['eco_worth_on'] && $this->settings['eco_rankings_on']) ? ("	
					<p class='message user_status'><img src='{$this->settings['img_url']}/eco_images/money.png' alt='{$this->lang->words['total_worth']}' title='{$this->lang->words['total_worth']}' />&nbsp;<strong>{$this->lang->words['total_worth']} {$this->lang->words['rank']}: <span style='font-size:1.25em'>#" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_worth_rank'] ) . "</span></strong></p>
				") : ("")) . "
				<table class='ipb_table'>
					<tr>
						<td style='font-weight:bold'>{$this->lang->words['total']} {$this->settings['eco_general_currency']}</td>
						<td>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_points'], $this->registry->ecoclass->decimal ) . "</td>
					</tr>
					" . (($this->settings['eco_worth_on']) ? ("	
						<tr>
							<td style='font-weight:bold'>{$this->lang->words['total_worth']}</td>
							<td>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_worth'], $this->registry->ecoclass->decimal ) . " </td>
						</tr>
					") : ("")) . "
					" . (($this->settings['eco_welfare_on']) ? ("
						<tr>
							<td style='font-weight:bold'>{$this->lang->words['total_welfare_short']}</td>
							<td>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_welfare'], $this->registry->ecoclass->decimal ) . "</td>
						</tr>
					") : ("")) . "
					<br />
				</table>
				</td>				
			</tr>
			<tr>
				<td style='text-align:right'>
					{$this->lang->words['reason']}:
				</td>
				<td style='text-align:left'>
					<input type='text' size='50%' maxlength='100' name='donation_reason' />
				</td>				
			</tr>
			<tr>
				<td style='text-align:right'>
					{$this->lang->words['amount']}:
				</td>
				<td style='text-align:left'>
					<input type='text' size='5' maxlength='20' name='donation_amount' />
				</td>				
			</tr>			
		</table>
		<fieldset class='submit'>
				<input type='submit' class='input_submit' value='{$this->lang->words['donate']}' />
		</form>		
		</fieldset>";
return $IPBHTML;
}

/* -- overviewRow --*/
function overviewRow($item='', $words='') {
$IPBHTML = "";
$IPBHTML .= "<tr class='header'>
				<th>
					<th colspan='5'>{$words['title']}</th>
				</th>
			</tr>
			<tr>
				<td style='width:4%'>
					<img src='{$this->settings['img_url']}/eco_images/{$words['image']}' alt='type' />
				</td>
				<td style='width:24%'>
					<span style='font-weight:bolder'>
						{$words['words1']}
					</span>
				</td>
				<td style='width:24%'>
					{$item['value1']}
				</td>				
				<td style='width:24%'>
					<span style='font-weight:bolder'>
						{$words['words2']}
					</span>
				</td>
				<td style='width:24%'>
					{$item['value2']}
				</td>
			</tr>";
return $IPBHTML;
}

/* -- overviewWrapper --*/
function overviewWrapper($content='') {
$IPBHTML = "";
$IPBHTML .= "<div class='maintitle'>{$this->lang->words['totals']}</div>
		<table class='ipb_table'>
			{$content}
		</table>";
return $IPBHTML;
}

/* -- pointButton --*/
function pointButton($member) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['pointButton'] ) )
{
$count_f7623c04ae5cc961cdfe422eefb84f76 = is_array($this->functionData['pointButton']) ? count($this->functionData['pointButton']) : 0;
$this->functionData['pointButton'][$count_f7623c04ae5cc961cdfe422eefb84f76]['member'] = $member;
}
$IPBHTML .= "" . ((!$this->settings['eco_pts_button_normal']) ? ("<li class='post_count desc lighter'>
	<a class='post_count desc lighter " . (($this->settings['eco_dons_on']) ? (" ibEconomy_MemPanePop' title='{$this->lang->words['view_my']} {$this->settings['eco_general_name']} {$this->lang->words['stats_and_donate_me_some']} {$this->settings['eco_general_currency']}'") : ("' title='{$this->lang->words['view_my']} {$this->settings['eco_general_name']} {$this->lang->words['profile']}' ")) . " id='do_member_{$member['member_id']}_{$this->request['app']}_{$this->request['showtopic']}{$this->request['topicID']}_{$this->request['st']}' href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=member&amp;id={$member['member_id']}'>{$member['eco_points']}</a> {$this->settings['eco_general_currency']}
</li>") : ("<div class='ipsLikeBar right clearfix' id='{$member['member_id']}'>
	<ul class='ipsList_inline'>
		<a class='ipsLikeButton ipsLikeButton_enabled rep_up " . (($this->settings['eco_dons_on']) ? (" ibEconomy_MemPanePop' title='{$this->lang->words['view_my']} {$this->settings['eco_general_name']} {$this->lang->words['stats_and_donate_me_some']} {$this->settings['eco_general_currency']}'") : ("' title='{$this->lang->words['view_my']} {$this->settings['eco_general_name']} {$this->lang->words['profile']}' ")) . " style='background: #acacac url({$this->settings['img_url']}/eco_images/money_add.png ) no-repeat top left;' id='do_member_{$member['member_id']}_{$this->request['app']}_{$this->request['showtopic']}{$this->request['topicID']}_{$this->request['st']}' href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=member&amp;id={$member['member_id']}'> {$this->settings['eco_general_currency']}: {$this->settings['eco_general_cursymb']}{$member['eco_points']}</a>
	</ul>
</div>")) . "";
return $IPBHTML;
}

/* -- profileTab --*/
function profileTab($assets, $transactions, $member, $shopItems) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['profileTab'] ) )
{
$count_34e5dd605e6316647d8a82470f3efbe6 = is_array($this->functionData['profileTab']) ? count($this->functionData['profileTab']) : 0;
$this->functionData['profileTab'][$count_34e5dd605e6316647d8a82470f3efbe6]['assets'] = $assets;
$this->functionData['profileTab'][$count_34e5dd605e6316647d8a82470f3efbe6]['transactions'] = $transactions;
$this->functionData['profileTab'][$count_34e5dd605e6316647d8a82470f3efbe6]['member'] = $member;
$this->functionData['profileTab'][$count_34e5dd605e6316647d8a82470f3efbe6]['shopItems'] = $shopItems;
}
$IPBHTML .= "<div id='pane_core:info' class='ipsLayout ipsLayout_withright ipsLayout_largeright clearfix' >						
	<div class='ipsLayout_content'> 
		<div class='general_box clearfix'> 
		<h3>{$this->lang->words['latest_purchases']}</h3><br />								
			<ul class='ipsList_data clearfix'>
				" . (($assets AND $this->settings['eco_assets_on']) ? ("
					{$assets}
					<br />
					<div class='right'>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=ibEconomy&amp;tab=global&amp;area=portfolio&amp;member_id={$member['member_id']}&amp;mname={$member['members_display_name']}", "public",'' ), "true", "" ) . "'>{$this->lang->words['view_more_assets']}&rarr;</a>
					</div>
				") : ("
					<p class='desc'>
						{$this->lang->words['none_to_show_ass']}
					</p>
				")) . " 
			</ul><br /> 
		</div>  
	</div> 
	<div class='ipsLayout_right'>
		" . (($this->settings['eco_worth_on']) ? ("" . (($member['eco_worth'] > 0) ? ("
				<div class='reputation positive' data-tooltip=\"{$this->lang->words['on_hand']}&nbsp; {$this->settings['eco_general_currency']}\">
					<span class='number'>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_worth'],$this->registry->ecoclass->decimal ) . "</span>
				</div>
			") : ("")) . "
			" . (($member['eco_worth'] < 0) ? ("
				<div class='reputation negative' data-tooltip=\"{$this->lang->words['on_hand']}&nbsp; {$this->settings['eco_general_currency']}\">
					<span class='number'>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_worth'],$this->registry->ecoclass->decimal ) . "</span>
				</div>		
			") : ("")) . "
			" . (($member['eco_worth'] == 0) ? ("
				<div class='reputation zero' data-tooltip=\"{$this->lang->words['on_hand']}&nbsp; {$this->settings['eco_general_currency']}\">
					<span class='number'>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_worth'],$this->registry->ecoclass->decimal ) . "</span>
				</div>		
			") : ("")) . "") : ("" . (($member['eco_points'] > 0) ? ("
				<div class='reputation positive' data-tooltip=\"{$this->lang->words['on_hand']}&nbsp; {$this->settings['eco_general_currency']}\">
					<span class='number'>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_points'],$this->registry->ecoclass->decimal ) . "</span>
				</div>
			") : ("")) . "
			" . (($member['eco_points'] < 0) ? ("
				<div class='reputation negative' data-tooltip=\"{$this->lang->words['on_hand']}&nbsp; {$this->settings['eco_general_currency']}\">
					<span class='number'>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_points'],$this->registry->ecoclass->decimal ) . "</span>
				</div>		
			") : ("")) . "
			" . (($member['eco_points'] == 0) ? ("
				<div class='reputation zero' data-tooltip=\"{$this->lang->words['on_hand']}&nbsp; {$this->settings['eco_general_currency']}\">
					<span class='number'>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $member['eco_points'],$this->registry->ecoclass->decimal ) . "</span>
				</div>		
			") : ("")) . "")) . "
		<br /> 
		" . (($this->settings['eco_shopitems_on']) ? ("<div class='general_box clearfix' id='friends_overview'> 
				<h3>{$this->lang->words['my_shopitems_area']}</h3> 
				<div class='ipsPad'> 
					" . (($shopItems) ? ("
						{$shopItems}
					") : ("
						<p class='desc'>
							{$this->lang->words['none_to_show_shopitems']}
						</p>
					")) . "
				</div> 
			</div>") : ("")) . "
		" . (($this->settings['eco_transactions_on']) ? ("<div class='general_box clearfix'> 
			<h3>{$this->lang->words['latest_transactions']}</h3> 
				<ul class='ipsPad'>	
					" . (($transactions) ? ("
						{$transactions}
						<br />
						<div class='right' style='padding-bottom:10px;'>
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=ibEconomy&amp;tab=global&amp;area=transactions&amp;member_id={$member['member_id']}&amp;mname={$member['members_display_name']}", "public",'' ), "true", "" ) . "'>{$this->lang->words['view_more_transactions']}&rarr;</a>
						</div>
					") : ("
						<p class='desc'>
							{$this->lang->words['none_to_show_trans']}
						</p>
					")) . "
				</ul> 
			</div>") : ("")) . "
		<br /><br /> 
	</div>
 </div>";
return $IPBHTML;
}

/* -- profileTabItemRow --*/
function profileTabItemRow($asset) {
$IPBHTML = "";
$IPBHTML .= "<div class=\"ipsBox_container ipsPad\">
		<a href='{$this->settings['base_url']}app=ibEconomy&amp;tab={$asset['tab']}&amp;area=single&amp;type={$asset['p_type']}&amp;id={$asset['p_type_id']}&amp;bank_type={$asset['p_type_class']}' title='{$this->lang->words['view_item']}' class='ipsUserPhotoLink left'>{$asset['image_link_prf_tab']}</a>
		<div class=\"left\"></div>
		<div class=\"ipsBox_withphoto status_content\">
			<div>
				<h4>
					<a href='{$this->settings['base_url']}app=ibEconomy&amp;tab={$asset['tab']}&amp;area=single&amp;type={$asset['p_type']}&amp;id={$asset['p_type_id']}&amp;bank_type={$asset['p_type_class']}' />{$asset['title']} </a>
					<a href='{$this->settings['base_url']}app=ibEconomy&amp;tab={$asset['tab']}&amp;area=single&amp;type={$asset['p_type']}&amp;id={$asset['p_type_id']}&amp;bank_type={$asset['p_type_class']}'' class='__item __id{$asset['p_type_id']}__type_{$asset['p_type']}_{$asset['p_type_class']}' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a>
				</h4>
				<span class=\"desc lighter blend_links\">
					{$asset['purchased_text']}:&nbsp;{$asset['purchase_date']}&nbsp;({$asset['quantity']})
				</span>
			</div>
			<div class=\"status_feedback\">
				<div style='padding-left:10px'>
					<ul class=\"ipsList_withtinyphoto reply row2 ipsPad\">
						<li>
							{$this->lang->words['cost']}:&nbsp;{$asset['cost']} &middot; {$asset['total_text']}:&nbsp;{$asset['total_bought']}
						</li>
					</ul>
				</div>
				<div class=\"status_mini_wrap row2 altrow\" id=\"statusMaxWrap-32\" style=\"display: none;\">
					<img src=\"http://testib3two.ibbookie.com/public/style_images/master/locked_replies.png\" title=\"This status update has reached the maximum number of replies allowed\" alt=\"x\"> This status update has reached the maximum number of replies allowed
				</div>
			</div>
		</div>
	</div><br>";
return $IPBHTML;
}

/* -- profileTabLogRow --*/
function profileTabLogRow($log) {
$IPBHTML = "";
$IPBHTML .= "<li><img src='{$this->settings['img_url']}/eco_images/{$log['l_image']}' title='{$log['l_action']}' alt='type' /> {$log['l_action']}
<span class='desc'>{$log['l_log']}<br />{$log['l_date']}</span></li><br />";
return $IPBHTML;
}

/* -- setting_group --*/
function setting_group($setting, $settingRows) {
$IPBHTML = "";
$IPBHTML .= "<br />
		<table class='ipb_table'>
			<tr class='header'>
				<th width='75%'><img src='{$setting['image_link']}' /> {$setting['title']}</th>
				<th>&nbsp;</th>
			</tr>
			{$settingRows}		
		</table>";
return $IPBHTML;
}

/* -- setting_row --*/
function setting_row($setting) {
$IPBHTML = "";
$IPBHTML .= "<tr>
							<td>{$setting['words']}</td>
							<td>{$setting['value']}</td>
						</tr>";
return $IPBHTML;
}

/* -- settings --*/
function settings($mySettings, $myPluginSettings) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['settings'] ) )
{
$count_996e0181ec32ab7ca1b7478438ba3f77 = is_array($this->functionData['settings']) ? count($this->functionData['settings']) : 0;
$this->functionData['settings'][$count_996e0181ec32ab7ca1b7478438ba3f77]['mySettings'] = $mySettings;
$this->functionData['settings'][$count_996e0181ec32ab7ca1b7478438ba3f77]['myPluginSettings'] = $myPluginSettings;
}
$IPBHTML .= "<div class='maintitle'>{$this->lang->words['settings']}</div>
		<table class='ipb_table'>
			<tr class='header'>
				<th width='75%'><img src='{$this->settings['img_url']}/eco_images/money.png' /> {$this->lang->words['global']}</th>
				<th>&nbsp;</th>
			</tr>
			<tr>
				<td>{$this->lang->words['can_access']} {$this->settings['eco_general_name']}</td>
				<td><img src='{$this->settings['img_url']}/accept.png' /></td>
			</tr>
			" . (($this->settings['eco_transactions_on']) ? ("	
			<tr>
				<td>{$this->lang->words['can_access_transactions']}</td>
				<td><img src='{$this->settings['img_url']}/{$mySettings['transaction']['image']}' /></td>
			</tr>
			") : ("")) . "
			" . (($this->settings['eco_assets_on']) ? ("	
			<tr>
				<td>{$this->lang->words['can_access_assets']}</td>
				<td><img src='{$this->settings['img_url']}/{$mySettings['asset']['image']}' /></td>
			</tr>
			") : ("")) . "
			<tr>
				<td>{$this->lang->words['my_max']} {$this->settings['eco_general_currency']}</td>
				<td>" . (($this->memberData['g_eco_max_pts'] > 0 ) ? ("{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_max_pts'], $this->registry->ecoclass->decimal ) . "") : ("{$this->lang->words['n_a']}")) . "</td>
			</tr>
			<tr>
				<td>{$this->settings['eco_general_currency']} {$this->lang->words['per_new_topic']}</td>
				<td>" . (($this->settings['eco_pts_per_topic']) ? ("<img src='{$this->settings['img_url']}/accept.png' />") : ("<img src='{$this->settings['img_url']}/cross.png' />")) . "</td>
			</tr>	
			<tr>
				<td>{$this->settings['eco_general_currency']} {$this->lang->words['per_reply']}</td>
				<td>" . (($this->settings['eco_pts_per_reply']) ? ("<img src='{$this->settings['img_url']}/accept.png' />") : ("<img src='{$this->settings['img_url']}/cross.png' />")) . "</td>
			</tr>	
			<tr>
				<td>{$this->settings['eco_general_currency']} {$this->lang->words['per_reply_to_own_thread']}</td>
				<td>" . (($this->settings['eco_pts_per_get_reply']) ? ("<img src='{$this->settings['img_url']}/accept.png' />") : ("<img src='{$this->settings['img_url']}/cross.png' />")) . "</td>
			</tr>							
			<tr>
				<td>{$this->lang->words['my']} {$this->settings['eco_general_currency']} {$this->lang->words['forum_pts_multiplier']}</td>
				<td>" . (($this->memberData['g_eco_frm_ptsx'] > 0 ) ? ("" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_frm_ptsx'], 2 ) . "{$this->lang->words['%']}") : ("{$this->lang->words['n_a']}")) . "</td>
			</tr>	
			<tr>
				<td>{$this->lang->words['minimum_ppd_for_interest']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_interest_restrict_ppd'], 2 ) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['recent_activity']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_interest_restrict_act'] ) . " {$this->lang->words['days']}</td>
			</tr>
		</table>
		" . (($this->settings['eco_banks_on']) ? ("<br />
		<table class='ipb_table'>
			<tr class='header'>
				<th width='75%'><img src='{$this->settings['img_url']}/eco_images/building_key.png' /> {$this->lang->words['banks']}</th>
				<th>&nbsp;</th>
			</tr>
			<tr>
				<td>{$this->lang->words['can_access_banks']}</td>
				<td><img src='{$this->settings['img_url']}/{$mySettings['bank']['image']}' /></td>
			</tr>
			<tr>
				<td>{$this->lang->words['my_max_balance_per_account']}</td>
				<td>" . (($this->memberData['g_eco_bank_max']) ? ("{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_bank_max'], $this->registry->ecoclass->decimal ) . "") : ("{$this->lang->words['n_a']}")) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['bank_interest_cycle']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_banks_cycle'] ) . " {$this->lang->words['days']}</td>
			</tr>
		</table>") : ("")) . "
		" . (($this->settings['eco_stocks_on']) ? ("<br />
		<table class='ipb_table'>
			<tr class='header'>
				<th width='75%'><img src='{$this->settings['img_url']}/eco_images/chart_curve.png' /> {$this->lang->words['stocks']}</th>
				<th>&nbsp;</th>
			</tr>
			<tr>
				<td>{$this->lang->words['can_access_stocks']}</td>
				<td><img src='{$this->settings['img_url']}/{$mySettings['stock']['image']}' /></td>
			</tr>
			<tr>
				<td>{$this->lang->words['max_shares']}</td>
				<td>" . (($this->memberData['g_eco_stock_max']) ? ("" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_stock_max'] ) . "") : ("{$this->lang->words['n_a']}")) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['stock_value_cycle']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_stocks_cycle'] ) . " {$this->lang->words['minutes']}</td>
			</tr>
			<tr>
				<td>{$this->lang->words['stock_purch_tax']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_stocks_buy_fee'], 2 ) . "{$this->lang->words['%']}</td>
			</tr>
			<tr>
				<td>{$this->lang->words['stock_sell_tax']} </td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_stocks_sell_fee'], 2 ) . "{$this->lang->words['%']}</td>
			</tr>
		</table>") : ("")) . "
		" . (($this->settings['eco_ccs_on']) ? ("<br />
		<table class='ipb_table'>
			<tr class='header'>
				<th width='75%'><img src='{$this->settings['img_url']}/eco_images/creditcards.png' /> {$this->lang->words['credit_cards']}</th>
				<th>&nbsp;</th>
			</tr>
			<tr>
				<td>{$this->lang->words['can_access_ccs']}</td>
				<td><img src='{$this->settings['img_url']}/{$mySettings['cc']['image']}' /></td>
			</tr>
			<tr>
				<td>{$this->lang->words['max_debt_total']}</td>
				<td>" . (($this->memberData['g_eco_max_cc_debt']) ? ("{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_max_cc_debt'],$this->registry->ecoclass->decimal ) . "") : ("{$this->lang->words['n_a']}")) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['min_payment_due_cycle']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_ccs_bill_rate'] ) . " {$this->lang->words['days']}</td>
			</tr>
			<tr>
				<td>{$this->lang->words['max_balance_transfer_per_card']}</td>
				<td>" . (($this->memberData['g_eco_bal_trnsfr_max']) ? ("{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_bal_trnsfr_max'],$this->registry->ecoclass->decimal ) . "") : ("{$this->lang->words['n_a']}")) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['max_cash_advance_per_card']}</td>
				<td>" . (($this->memberData['g_eco_cash_adv_max']) ? ("{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_cash_adv_max'],$this->registry->ecoclass->decimal ) . "") : ("{$this->lang->words['n_a']}")) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['min_due_at_cycle']} </td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_ccs_min_pay'], 2 ) . "{$this->lang->words['%']}</td>
			</tr>
		</table>") : ("")) . "
		" . (($this->settings['eco_lts_on']) ? ("<br />
		<table class='ipb_table'>
			<tr class='header'>
				<th width='75%'><img src='{$this->settings['img_url']}/eco_images/bar_graph.png' /> {$this->lang->words['lts']}</th>
				<th>&nbsp;</th>
			</tr>
			<tr>
				<td>{$this->lang->words['can_access_lts']}</td>
				<td><img src='{$this->settings['img_url']}/{$mySettings['lt']['image']}' /></td>
			</tr>
			<tr>
				<td>{$this->lang->words['max_invest_per_invest']}</td>
				<td>" . (($this->memberData['g_eco_lt_max']) ? ("{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_lt_max'], $this->registry->ecoclass->decimal ) . "") : ("{$this->lang->words['n_a']}")) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['invest_balance_cycle']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_lts_cycle'] ) . " {$this->lang->words['days']}</td>
			</tr>
			<tr>
				<td>{$this->lang->words['investing_tax']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_lts_buy_fee'], 2 ) . "{$this->lang->words['%']}</td>
			</tr>
			<tr>
				<td>{$this->lang->words['invest_cashout_tax']} </td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_lts_sell_fee'], 2 ) . "{$this->lang->words['%']}</td>
			</tr>
		</table>") : ("")) . "
		" . (($this->settings['eco_shopitems_on']) ? ("<br />
		<table class='ipb_table'>
			<tr class='header'>
				<th width='75%'><img src='{$this->settings['img_url']}/eco_images/tag_blue.png' /> {$this->lang->words['shop']}</th>
				<th>&nbsp;</th>
			</tr>
			<tr>
				<td>{$this->lang->words['can_access_shopitems']}</td>
				<td><img src='{$this->settings['img_url']}/{$mySettings['shopitem']['image']}' /></td>
			</tr>
			<tr>
				<td>{$this->lang->words['item_sales_tax']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_shop_tax'],2 ) . "{$this->lang->words['%']}</td>
			</tr>
			<tr>
				<td>{$this->lang->words['item_sell_back_tax']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_shop_sell_fee'],2 ) . "{$this->lang->words['%']}</td>
			</tr>
			" . (($this->settings['eco_shop_trading']) ? ("
			<tr>
				<td>{$this->lang->words['item_trade_tax']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_shop_trade_tax'],2 ) . "{$this->lang->words['%']}</td>
			</tr>
			") : ("")) . "
		</table>") : ("")) . "
		" . (($this->settings['eco_welfare_on']) ? ("<br />
		<table class='ipb_table'>
			<tr class='header'>
				<th width='75%'><img src='{$this->settings['img_url']}/eco_images/coins_add.png' /> {$this->lang->words['welfare']}</th>
				<th>&nbsp;</th>
			</tr>
			<tr>
				<td>{$this->lang->words['can_access_welfare']}</td>
				<td><img src='{$this->settings['img_url']}/{$mySettings['welfare']['image']}' /></td>
			</tr>
			<tr>
				<td>{$this->lang->words['max_welfare_per_check']}</td>
				<td>" . (($this->memberData['g_eco_welfare_max']) ? ("{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_welfare_max'], $this->registry->ecoclass->decimal ) . "") : ("{$this->lang->words['n_a']}")) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['max']} {$this->settings['eco_general_currency']} {$this->lang->words['to_qualify']}</td>
				<td>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_welfare_max_pts'],$this->registry->ecoclass->decimal ) . "</td>
			</tr>
			" . (($this->settings['eco_worth_on']) ? ("	
				<tr>
					<td>{$this->lang->words['max_worth']} {$this->lang->words['to_qualify']}</td>
					<td>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_welfare_max_worth'],$this->registry->ecoclass->decimal ) . "</td>
				</tr>
			") : ("")) . "
			<tr>
				<td>{$this->lang->words['max_welfare_recieved']} {$this->lang->words['to_qualify']}</td>
				<td>{$this->settings['eco_general_cursymb']}" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_welfare_max_wf'] ) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['min_posts']} {$this->lang->words['to_qualify']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_welfare_min_posts'] ) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['min_ppd']} {$this->lang->words['to_qualify']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_welfare_min_ppd'],2 ) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['min_days_as_mem']} {$this->lang->words['to_qualify']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_welfare_min_join'] ) . " {$this->lang->words['days']}</td>
			</tr>
			<tr>
				<td>{$this->lang->words['welfare_activity']} {$this->lang->words['to_qualify']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_welfare_act'] ) . " {$this->lang->words['days']}</td>
			</tr>
			<tr>
				<td>{$this->lang->words['qualifications_above_apply_every_check']}</td>
				<td>" . (($this->settings['eco_welfare_res_alwys']) ? ("<img src='{$this->settings['img_url']}/accept.png' />") : ("<img src='{$this->settings['img_url']}/cross.png' />")) . "</td>
			</tr>						
			<tr>
				<td>{$this->lang->words['welfare_cycle']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_welfare_cycle'] ) . " {$this->lang->words['days']}</td>
			</tr>
		</table>") : ("")) . "
		" . (($this->settings['eco_loans_on']) ? ("<br />
		<table class='ipb_table'>
			<tr class='header'>
				<th width='75%'><img src='{$this->settings['img_url']}/eco_images/money_add.png' /> {$this->lang->words['loans']}</th>
				<th>&nbsp;</th>
			</tr>
			<tr>
				<td>{$this->lang->words['can_access_loans']}</td>
				<td><img src='{$this->settings['img_url']}/{$mySettings['loan']['image']}' /></td>
			</tr>
			<tr>
				<td>{$this->lang->words['max_loan_debt']}</td>
				<td>" . (($this->memberData['g_eco_welfare_max']) ? ("{$this->settings['g_eco_max_loan_debt']}" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_max_loan_debt'], $this->registry->ecoclass->decimal ) . "") : ("{$this->lang->words['n_a']}")) . "</td>
			</tr>
			<tr>
				<td>{$this->lang->words['loan_apr_cycle']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_loans_apr_cycle'] ) . " {$this->lang->words['days']}</td>
			</tr>
			<tr>
				<td>{$this->lang->words['loan_pen_cycle']}</td>
				<td>" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_loans_pen_cycle'] ) . " {$this->lang->words['days']}</td>
			</tr>
		</table>") : ("")) . "
		" . (($this->settings['eco_lotterys_on']) ? ("<br />
		<table class='ipb_table'>			
			<tr class='header'>
				<th width='75%'><img src='{$this->settings['img_url']}/eco_images/lotto.png' /> {$this->lang->words['lottery']}</th>
				<th>&nbsp;</th>
			</tr>
				<tr>
					<td>{$this->lang->words['can_buy_lotto_tickets']}</td>
					<td><img src='{$this->settings['img_url']}/{$mySettings['lottery']['image']}' /></td>
				</tr>
				<tr>
					<td>{$this->lang->words['max_lotto_tickets']}</td>
					<td>" . (($this->memberData['g_eco_lottery_tix']) ? ("" . $this->registry->getClass('class_localization')->formatNumber( $this->memberData['g_eco_lottery_tix'] ) . "") : ("" . $this->registry->getClass('class_localization')->formatNumber( $this->settings['eco_lotto_def_max_tix'] ) . "")) . "</td>
				</tr>
				<tr>
					<td>{$this->lang->words['my_chances_of_winning_a_lotto']}</td>
					<td>{$this->memberData['g_eco_lottery_odds']}</td>
				</tr>		
		</table>") : ("")) . "
		{$myPluginSettings}";
return $IPBHTML;
}

/* -- standings_row --*/
function standings_row($member) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['standings_row'] ) )
{
$count_644356f406f3df8c06101f2f5fb6437d = is_array($this->functionData['standings_row']) ? count($this->functionData['standings_row']) : 0;
$this->functionData['standings_row'][$count_644356f406f3df8c06101f2f5fb6437d]['member'] = $member;
}
$IPBHTML .= "<li id='member_id_{$member['member_id']}' class='ipsPad clearfix member_entry {$member['row_style']}'>
		<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink left'><img src='{$member['pp_small_photo']}' alt=\"{$member['members_display_name']}{$this->lang->words['users_photo']}\" class='ipsUserPhoto ipsUserPhoto_medium' /></a>
		<div class='ipsBox_withphoto'>
			<ul class='ipsList_inline right'>
				" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $member['member_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("" . ((IPSMember::checkFriendStatus( $member['member_id'] )) ? ("
						<li class='mini_friend_toggle is_friend' id='friend_mlist_{$member['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=list&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id={$member['member_id']}&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}' class='ipsButton_secondary'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a></li>
					") : ("
						<li class='mini_friend_toggle is_not_friend' id='friend_mlist_{$member['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=list&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id={$member['member_id']}&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['add_friend']}' class='ipsButton_secondary'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a></li>								
					")) . "") : ("")) . "
				" . (($this->memberData['g_use_pm'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' ) && $member['member_id'] != $this->memberData['member_id']) ? ("
					<li class='pm_button' id='pm_xxx_{$member['pp_member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=list&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$member['pp_member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['pm_member']}' class='ipsButton_secondary'>" . $this->registry->getClass('output')->getReplacement("send_msg") . "</a></li>
				") : ("")) . "
				" . (($this->settings['eco_assets_on'] AND $this->memberData['g_eco_asset']) ? ("
					<li><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&area=portfolio&amp;member_id={$member['member_id']}&amp;mname={$member['members_display_name']}' class='ipsButton_secondary' title='{$this->lang->words['view_assets']}'>" . $this->registry->getClass('output')->getReplacement("find_topics_link") . "</a></li>
				") : ("")) . "
				" . (($this->settings['eco_transactions_on'] AND $this->memberData['g_eco_transaction'] AND (!$this->settings['eco_general_only_my_trans'] || $this->memberData['g_eco_edit_pts'])) ? ("
					<li><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&area=transactions&amp;member_id={$member['member_id']}&amp;mname={$member['members_display_name']}' class='ipsButton_secondary' title='{$this->lang->words['view_transactions']}'>" . $this->registry->getClass('output')->getReplacement("blog_link") . "</a></li>
				") : ("")) . "				
			</ul>
			
			<h3 class='ipsType_subtitle'>
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($member) : '' ) . "
			</h3>
			" . (($this->settings['eco_worth_on']) ? ("" . (($member['eco_worth'] == 0 || !$member['eco_worth']) ? ("
					<p class='reputation zero ipsType_small left' data-tooltip=\"" . sprintf( $this->lang->words['member_has_x_pts_total_worth'], $member['members_display_name'], $member['formatted_worth'], $this->settings['eco_general_currency'] ) . "\">
				") : ("")) . "
				" . (($member['eco_worth'] > 0) ? ("
					<p class='reputation positive ipsType_small left' data-tooltip=\"" . sprintf( $this->lang->words['member_has_x_pts_total_worth'], $member['members_display_name'], $member['formatted_worth'], $this->settings['eco_general_currency'] ) . "\">
				") : ("")) . "
				" . (($member['eco_worth'] < 0) ? ("
					<p class='reputation negative ipsType_small left' data-tooltip=\"" . sprintf( $this->lang->words['member_has_x_pts_total_worth'], $member['members_display_name'], $member['formatted_worth'], $this->settings['eco_general_currency'] ) . "\">
				") : ("")) . "							
						<span class='number'>{$this->settings['eco_general_cursymb']}{$member['formatted_worth']}</span>
					</p>") : ("" . (($member['eco_points'] == 0 || !$member['eco_points']) ? ("
					<p class='reputation zero ipsType_small left' data-tooltip=\"" . sprintf( $this->lang->words['member_has_x_pts'], $member['members_display_name'], $member['formatted_pts'], $this->settings['eco_general_currency'] ) . "\">
				") : ("")) . "
				" . (($member['eco_points'] > 0) ? ("
					<p class='reputation positive ipsType_small left' data-tooltip=\"" . sprintf( $this->lang->words['member_has_x_pts'], $member['members_display_name'], $member['formatted_pts'], $this->settings['eco_general_currency'] ) . "\">
				") : ("")) . "
				" . (($member['eco_points'] < 0) ? ("
					<p class='reputation negative ipsType_small left' data-tooltip=\"" . sprintf( $this->lang->words['member_has_x_pts'], $member['members_display_name'], $member['formatted_pts'], $this->settings['eco_general_currency'] ) . "\">
				") : ("")) . "							
						<span class='number'>{$this->settings['eco_general_cursymb']}{$member['formatted_pts']}</span>
					</p>")) . "			
			<span class='desc'>
				" . (($this->settings['eco_worth_on']) ? ("{$member['formatted_pts']} {$this->lang->words['on_hand']} {$this->settings['eco_general_currency']}
					" . ((!$this->settings['eco_rankings_on']) ? ("<br />{$this->lang->words['member_joined']} " . $this->registry->getClass('class_localization')->getDate($member['joined'],"joined", 0) . "") : ("")) . "") : ("
					{$this->lang->words['member_joined']} " . $this->registry->getClass('class_localization')->getDate($member['joined'],"joined", 0) . "
				")) . "
				" . (($this->settings['eco_rankings_on']) ? ("<br />{$member['eco_worth_rank']}") : ("")) . "
			</span>
		</div>
	</li>";
return $IPBHTML;
}

/* -- standings_wrapper --*/
function standings_wrapper($content, $pages, $active) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['standings_wrapper'] ) )
{
$count_c7dcfb61b8c5e78a4dfda09ac3433133 = is_array($this->functionData['standings_wrapper']) ? count($this->functionData['standings_wrapper']) : 0;
$this->functionData['standings_wrapper'][$count_c7dcfb61b8c5e78a4dfda09ac3433133]['content'] = $content;
$this->functionData['standings_wrapper'][$count_c7dcfb61b8c5e78a4dfda09ac3433133]['pages'] = $pages;
$this->functionData['standings_wrapper'][$count_c7dcfb61b8c5e78a4dfda09ac3433133]['active'] = $active;
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("memberlist", "0" ) . "
			<div class='maintitle ipsFilterbar'>
				<ul class='ipsList_inline ipsType_smaller'>
					<li " . (($this->request['sort'] == 'members_display_name') ? ("class='active'") : ("")) . ">
						<a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=rankings&amp;sort=members_display_name&amp;sw={$active['sw']}' title='{$this->lang->words['sort_by_member_name']}'>{$this->lang->words['member_name']}</a> " . (($this->request['sort'] == 'members_display_name') ? ("<img src='{$this->settings['img_url']}/eco_images/{$active['sw']}.png' title='{$this->lang->words['currently_sorted']}: {$this->request['sw']}' />") : ("")) . "
					</li>
					" . (($this->settings['eco_welfare_on']) ? ("<li " . (($this->request['sort'] == 'eco_welfare') ? ("class='active'") : ("")) . ">
							<a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=rankings&amp;sort=eco_welfare&amp;sw={$active['sw']}' title='{$this->lang->words['sort_by_total_welfare']}'>{$this->lang->words['total_welfare_received']}</a> " . (($this->request['sort'] == 'eco_welfare') ? ("<img src='{$this->settings['img_url']}/eco_images/{$this->request['sw']}.png' title='{$this->lang->words['currently_sorted']}: {$this->request['sw']}' />") : ("")) . "
						</li>") : ("")) . "
					<li " . (($this->request['sort'] == 'points' || !$this->settings['eco_worth_on'] && !$this->request['sort']) ? ("class='active'") : ("")) . ">
						<a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=rankings&amp;sort=points&amp;sw={$active['sw']}' title='{$this->lang->words['sort_by_total']} {$this->settings['eco_general_currency']}'>{$this->lang->words['total']} {$this->settings['eco_general_currency']}</a> " . (($this->request['sort'] == 'points') ? ("<img src='{$this->settings['img_url']}/eco_images/{$this->request['sw']}.png' title='{$this->lang->words['currently_sorted']}: {$this->request['sw']}' />") : ("")) . "		
					</li>
					" . (($this->settings['eco_worth_on']) ? ("<li " . (($this->request['sort'] == 'eco_worth' || $this->settings['eco_worth_on'] && !$this->request['sort']) ? ("class='active'") : ("")) . ">
							<a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=rankings&amp;sort=eco_worth&amp;sw={$active['sw']}' title='{$this->lang->words['sort_by_total_worth']}'>{$this->lang->words['total_worth']}</a> " . (($this->request['sort'] == 'eco_worth' || $this->request['sort'] == '') ? ("<img src='{$this->settings['img_url']}/eco_images/{$this->request['sw']}.png' title='{$this->lang->words['currently_sorted']}: {$this->request['sw']}' />") : ("")) . "
						</li>") : ("")) . "
				</ul>
			</div>		
			<table class='ipb_table'>
				<div class='ipsBox_container ipsPad' id='mlist_content'>
					<ul class='ipsMemberList'>
						{$content}
					</ul>
				</div>				
			</table>
<script type='text/javascript'>
	$(\"mlist_content\").setStyle( { minHeight: $('mlist_tabs').measure('margin-box-height') + 5 + \"px\" } );
</script>			
			<div style='margin:10px;'>
				{$pages}
			</div>";
return $IPBHTML;
}

/* -- stats --*/
function stats($active, $totals) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['stats'] ) )
{
$count_3e6f493c273c24fd3df49bb10a0e58ac = is_array($this->functionData['stats']) ? count($this->functionData['stats']) : 0;
$this->functionData['stats'][$count_3e6f493c273c24fd3df49bb10a0e58ac]['active'] = $active;
$this->functionData['stats'][$count_3e6f493c273c24fd3df49bb10a0e58ac]['totals'] = $totals;
}
$IPBHTML .= "" . (($this->settings['eco_general_show_stats']) ? ("<br />
	" . (($this->settings['eco_general_show_totals']) ? ("<div id='board_stats'>		
			<ul class='ipsType_small ipsList_inline'> 
				<li class='clear'> 
					<span class='value'>{$totals['total_points']}</span> 
					{$this->lang->words['total']} {$this->settings['eco_general_currency']}
				</li> 
				" . (($this->settings['eco_worth_on']) ? ("
					<li class='clear'> 
						<span class='value'>{$totals['total_worth']}</span> 
						{$this->lang->words['total_worth']}
					</li> 
				") : ("")) . "				
				" . (($this->settings['eco_shopitems_on']) ? ("<li class='clear'> 
						" . ((is_array( $totals['newest_item'] ) && count( $totals['newest_item'] ) ) ? ("
							<span class='value'>{$totals['newest_item']['si_title']}</span> <a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=shop&amp;area=single&amp;type=item&amp;id={$totals['newest_item']['si_id']}' class='__item __id{$totals['newest_item']['si_id']}__type_shopitem_Item' title='{$this->lang->words['view_further_details']}'><img src='{$this->settings['img_url']}/user_popup.png'></a>
						") : ("
							<span class='value'>{$totals['newest_item']}</span> 
						")) . "
						{$this->lang->words['newest_item']}
					</li>") : ("")) . "
				<li class='clear'> 
					<span class='value'>{$totals['item_count']}</span> 
					{$this->lang->words['num_shop_items']}
				</li> 
				<li class='clear' data-tooltip='{$totals['most_time']}'> 
					<span class='value'>{$totals['most_online']}</span> 
					{$this->lang->words['online_at_once']}
				</li>				
			</ul> 
		</div>") : ("")) . "
	" . (($this->settings['eco_general_show_active']) ? ("<div id='board_statistics' class='statistics clearfix'> 
			<ul id='stat_links' class='ipsList_inline right ipsType_small'> 
				" . (($this->settings['eco_shopitems_on'] && $this->memberData['g_eco_shopitem']) ? ("	
					<li><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=me&amp;area=my_shopitems' title='{$this->lang->words['view_my_shopitems']}'>{$this->lang->words['my_shopitems']}</a></li>
				") : ("")) . "
			</ul> 
			<h4 class='statistics_head'>{$active['TOTAL']} {$this->lang->words['active_users_text']} {$this->lang->words['active_users']}</h4> 
			<p class='statistics_brief desc'> 
				<span class='desc'>{$active['MEMBERS']} {$this->lang->words['members']}, {$active['GUESTS']} {$this->lang->words['guests']}, {$active['ANON']} {$this->lang->words['anon_users']} </span>
			</p> <br /> 
			" . ((count($active['NAMES'])) ? ("
				<p>
					<span class='name'>" . implode( ",</span> <span class='name'>", $active['NAMES'] ) . "</span>					
				</p>
			") : ("")) . "
		</div>") : ("")) . "") : ("")) . "";
return $IPBHTML;
}

/* -- tab --*/
function tab($isActive, $tabName, $tabLangName, $title) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['tab'] ) )
{
$count_6a10eb6038485fc50d83f402b72416f2 = is_array($this->functionData['tab']) ? count($this->functionData['tab']) : 0;
$this->functionData['tab'][$count_6a10eb6038485fc50d83f402b72416f2]['isActive'] = $isActive;
$this->functionData['tab'][$count_6a10eb6038485fc50d83f402b72416f2]['tabName'] = $tabName;
$this->functionData['tab'][$count_6a10eb6038485fc50d83f402b72416f2]['tabLangName'] = $tabLangName;
$this->functionData['tab'][$count_6a10eb6038485fc50d83f402b72416f2]['title'] = $title;
}
$IPBHTML .= "<li " . (($isActive) ? ("class='active'") : ("")) . ">
						<a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=$tabName' title='{$title}'>{$tabLangName}</a>
				</li>&nbsp;";
return $IPBHTML;
}

/* -- tabs --*/
function tabs($active, $tabs) {
$IPBHTML = "";
$IPBHTML .= "<div class='maintitle ipsFilterbar'>
			<ul class='ipsList_inline'>
				{$tabs}
			</ul>
		</div>";
return $IPBHTML;
}

/* -- transactions_row --*/
function transactions_row($log) {
$IPBHTML = "";
$IPBHTML .= "<tr id='{$log['l_id']}'>
				<td>
					<img src='{$this->settings['img_url']}/eco_images/{$log['l_image']}' title='{$log['l_action']}' alt='type' />
				</td>
				<td>
					<span>{$log['l_date']}</span>
				</td>				
				<td>
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($log) : '' ) . "
				</td>			
				<td>
					<span>{$log['l_action']}</span>
				</td>
				<td>
					<span>{$log['l_log']}</span>
				</td>
			</tr>";
return $IPBHTML;
}

/* -- transactions_wrapper --*/
function transactions_wrapper($content='', $otherSW='', $pages='', $showMember) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['transactions_wrapper'] ) )
{
$count_0099784d86e58231e0f39594930ba622 = is_array($this->functionData['transactions_wrapper']) ? count($this->functionData['transactions_wrapper']) : 0;
$this->functionData['transactions_wrapper'][$count_0099784d86e58231e0f39594930ba622]['content'] = $content;
$this->functionData['transactions_wrapper'][$count_0099784d86e58231e0f39594930ba622]['otherSW'] = $otherSW;
$this->functionData['transactions_wrapper'][$count_0099784d86e58231e0f39594930ba622]['pages'] = $pages;
$this->functionData['transactions_wrapper'][$count_0099784d86e58231e0f39594930ba622]['showMember'] = $showMember;
}
$IPBHTML .= "<div class='maintitle ipsFilterbar'>
			<ul class='ipsList_inline ipsType_smaller'>
				<li " . (($this->request['sort'] == 'l_date') ? (" class='active'") : ("")) . "><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=transactions&amp;member_id={$this->request['member_id']}&amp;mname={$showMember}&amp;action={$this->request['action']}&amp;sort=l_date&amp;sw={$otherSW}'>{$this->lang->words['date']}</a></li>
				<li " . (($this->request['sort'] == 'm.members_display_name') ? (" class='active'") : ("")) . "><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=transactions&amp;member_id={$this->request['member_id']}&amp;mname={$showMember}&amp;action={$this->request['action']}&amp;sort=m.members_display_name&amp;sw={$otherSW}'>{$this->lang->words['member']}</a></li>
				<li " . (($this->request['sort'] == 'l_action') ? (" class='active'") : ("")) . "><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=transactions&amp;member_id={$this->request['member_id']}&amp;mname={$showMember}&amp;action={$this->request['action']}&amp;sort=l_action&amp;sw={$otherSW}'>{$this->lang->words['action']}</a></li>
				<li " . (($this->request['sort'] == 'l_log') ? (" class='active'") : ("")) . "><a href='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=transactions&amp;member_id={$this->request['member_id']}&amp;mname={$showMember}&amp;action={$this->request['action']}&amp;sort=l_log&amp;sw={$otherSW}'>{$this->lang->words['notes']}</a></li>
				<li " . (($showMember || $this->request['action']) ? (" class='active'") : ("")) . "><a href='#custom_menucontent' id='custom'>Custom</a></li>
			</ul>
		</div>
		<div id='custom_menucontent' class='ipbmenu_content ipsPad'>
			<form action='{$this->settings['base_url']}app=ibEconomy&amp;tab=global&amp;area=transactions' method='post'>
			" . ((!$this->settings['eco_general_only_my_trans'] || $this->memberData['g_eco_edit_pts']) ? ("
				<strong>{$this->lang->words['member']}</strong><br />
				<input type=\"text\" class='input_text' id='mem_name1' name=\"mem_name\" value=\"{$showMember}\" />
				<br /><br />
			") : ("")) . "
			<strong>{$this->lang->words['type']}</strong><br />
			<select name='action' class='input_select'>
				<optgroup label='{$this->lang->words['display']}...'>
					" . (($this->settings['eco_dons_on']) ? ("<option value='donation' " . (($this->request['action'] == 'donation') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['donations']}</option>") : ("")) . "" . (($this->settings['eco_banks_on'] || $this->settings['eco_stocks_on'] || $this->settings['eco_ccs_on'] || $this->settings['eco_lts_on'] || $this->settings['eco_shopitems_on']) ? ("<option value='purchase' " . (($this->request['action'] == 'purchase') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['purchases']}</option>") : ("")) . "" . (($this->settings['eco_loans_on']) ? ("<option value='loan' " . (($this->request['action'] == 'loan') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['loans']}</option>") : ("")) . "" . (($this->settings['eco_banks_on']) ? ("<option value='bank_withdrawal' " . (($this->request['action'] == 'bank_withdrawal') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['bank_withdrawals']}</option>
						<option value='bank_deposit' " . (($this->request['action'] == 'bank_deposit') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['bank_deposits']}</option>") : ("")) . "" . (($this->settings['eco_stocks_on']) ? ("<option value='sell_stock' " . (($this->request['action'] == 'sell_stock') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['sell_stocks']}</option>") : ("")) . "" . (($this->settings['eco_ccs_on']) ? ("<option value='cc_payment' " . (($this->request['action'] == 'cc_payment') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['cc_payments']}</option>") : ("")) . "" . (($this->settings['eco_lts_on']) ? ("<option value='sell_lt' " . (($this->request['action'] == 'sell_lt') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['sell_lts']}</option>") : ("")) . "" . (($this->settings['eco_shopitems_on']) ? ("<option value='sell_shopitem' " . (($this->request['action'] == 'sell_shopitem') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['sell_shopitems']}</option>
						<option value='trade_shopitem' " . (($this->request['action'] == 'trade_shopitem') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['trade_shopitems']}</option>
						<option value='use_shopitem' " . (($this->request['action'] == 'use_shopitem') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['use_shopitems']}</option>") : ("")) . "" . (($this->settings['eco_loans_on']) ? ("<option value='loan_payment' " . (($this->request['action'] == 'loan_payment') ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['loan_payments']}</option>") : ("")) . "
					<option value='' " . ((!$this->request['action']) ? ("selected='SELECTED'") : ("")) . ">{$this->lang->words['all']}</option>
			</select>
			<br /><br />
			<input type=\"submit\" value=\"Submit\" class=\"input_submit\" />
			</form>
		</div>
		<script type='text/javascript'>
			new ipb.Menu( $('custom'), $('custom_menucontent'), { stopClose: true } );
		</script>
		<table class='ipb_table'>
			<tr class='header'>
				<th width='5%'>&nbsp;</th>
				<th width='25%'>{$this->lang->words['date']}</th>
				<th width='15%'>{$this->lang->words['member']}</th>
				<th width='25%'>{$this->lang->words['action']}</th>
				<th width='25%'>{$this->lang->words['notes']}</th>
			</tr>
            {$content}
		</table>
		<div style='margin:10px;'>
			{$pages}
		</div>
<!--<script type=\"text/javascript\">
	document.observe(\"dom:loaded\", function(){
		var url = ipb.vars['base_url'] + 'app=core&module=ajax&section=findnames&do=get-member-names&secure_key=' + ipb.vars['secure_hash'] + '&name=';
		new ipb.Autocomplete( $('mem_name1'), { multibox: false, url: url, templates: { wrap: ipb.templates['autocomplete_wrap'], item: ipb.templates['autocomplete_item'] } } );
	});
</script>-->";
return $IPBHTML;
}

/* -- welcome --*/
function welcome($text) {
$IPBHTML = "";
$IPBHTML .= "<div class='message' style='margin:15px'>{$text}</div>";
return $IPBHTML;
}

/* -- wrapper --*/
function wrapper($active,$showpage) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ibEconomy', $this->_funcHooks['wrapper'] ) )
{
$count_f0301b0567330bce51457883e8fd396f = is_array($this->functionData['wrapper']) ? count($this->functionData['wrapper']) : 0;
$this->functionData['wrapper'][$count_f0301b0567330bce51457883e8fd396f]['active'] = $active;
$this->functionData['wrapper'][$count_f0301b0567330bce51457883e8fd396f]['showpage'] = $showpage;
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("board", "0" ) . "
<!--JS+CSS-->
<!--BUTTONS-->
<!--ANNOUNCE-->
<h2 class='hide'>{$this->lang->words['ibEconomy_title']}</h2>
<div id='board_index' class='ipsLayout ipsLayout_withright clearfix " . ((IPSCookie::get('hide_sidebar') == '1' || !$this->settings['eco_display_sidebar_on'] || in_array($this->registry->output->skin['set_id'], explode(',', $this->settings['eco_display_sb_skins']))) ? ("no_sidebar") : ("")) . "'>
	<!--SIDE_BAR-->
	<!--TABS-->
	<div class='ipsBox'> 
		<div class='ipsLayout ipsLayout_withleft ipsLayout_smallleft ipsVerticalTabbed clearfix'> 
			<!--AREAS-->
			<div class='ipsVerticalTabbed_content ipsLayout_content ipsBox_container' id='usercp_content'> 
				<div class='ipsPad'>
					{$showpage}
				</div>
			</div>				
		</div>
		<br class='clear' />
	</div>
</div>
<!--STATS-->
<!--FOOTER-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>